### ISSUE TITLE
RFE: Display Backup file name on Status of the backup CR

### ISSUE THREAD

**Issue by sowmyav27** [rancher/backup-restore-operator#10]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Deploy backup-restore chart on master-head
- Create a resourcet set
- Create a backup CR.
- The backup CR does not have Backup file name

**Expected Result:**
Backup CR can have the name of the backup file created in S3.
Recurring backups should also have the file name in the CR>

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): master-head commit id: `5e1b21b931`
- Installation option (single install/HA): HA

**Comment by mrajashree** [comment]
Available with the latest tag, you can get the latest commit from this branch https://github.com/mrajashree/charts/tree/backup-restore-sep-charts

**Comment by sowmyav27** [comment]
**Verified on master-head - commit id: `731b33e1` and backuprestore - tag `rc9`**

`filename: test-b2-0cf6e9d6-1d57-4959-a471-1b5a46e8abe5-2020-09-03T17#42#18Z.tar.gz` is available in the Backup CR.
