### ISSUE TITLE
Support Adding Annotations to the ServiceAccount 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/backup-restore-operator#104]
Enhancement. 

We should expose the option for setting annotations on the service account, so we can [associate an IAM role to a service account](https://docs.aws.amazon.com/eks/latest/userguide/specify-service-account-role.html) easily.

**Comment by jiaqiluo** [comment]
available in rancher-backup chart version 1.1.100+up1.1.1

**Comment by jiaqiluo** [comment]
can be tested on rancher-backup:`2.0.0+up2.0.0-rc2` in rancher:`master-head`

**Comment by sowmyav27** [comment]
**On master-head commit id: `4d18400`**

- Rancher backups version: `2.0.0+up2.0.0-rc2`
- Has in edit as yaml this:
```
serviceAccount:
  annotations: {}
```
