### ISSUE TITLE
[Backport] Support backup/restore installation on hardened cluster

### ISSUE THREAD

**Issue by cbron** [rancher/backup-restore-operator#109]
https://github.com/rancher/backup-restore-operator/issues/29

**Comment by jiaqiluo** [comment]
Can be tested in chart rancher-backup `1.2.0-rc2`

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `e89ad64`**

- Backup restore operator version - `v1.2.0-rc3`
- User is able to deploy the chart and take a backup
