### ISSUE TITLE
[Backport] Support Adding Annotations to the ServiceAccount

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/backup-restore-operator#111]
backport https://github.com/rancher/backup-restore-operator/issues/104 to the chart for Rancher v2.5.10

A new branch in this repo will be used for the rancher v2.5 line.

**Comment by jiaqiluo** [comment]
Can be tested in chart rancher-backup `1.2.0-rc2`

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `defd81cd`**

- Rancher backups version: `2.0.0+up2.0.0-rc2`
- Has in edit as yaml this:
```
serviceAccount:
  annotations: {}
```

- Setting a value, the rancher-backup after deploying, does show it has this annotation
```
serviceAccount:
  annotations:
    a: b
```
