### ISSUE TITLE
[Backport] Make sure backup/restore passes CIS hardened profile scan

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/backup-restore-operator#113]
https://github.com/rancher/backup-restore-operator/issues/34

**Comment by jiaqiluo** [comment]
Can be tested in chart rancher-backup `1.2.0-rc2`

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `e89ad64`**

- Backup restore operator version - `v1.2.0-rc3`
- User is able to deploy the chart and take a backup
- No new tests fail on running CIS 1.6 hardened scan after deploying chart
