### ISSUE TITLE
deny all ingress traffic 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/backup-restore-operator#116]
Enhancement.

Update the default [`networkPolicy`](https://github.com/rancher/backup-restore-operator/blob/af7d6a1de0ec51b1a51d9dae000f6f097add18d9/charts/rancher-backup/templates/hardened.yaml#L103-L116) to deny all ingress traffic because it does not needed for the app.

**Comment by jiaqiluo** [comment]
can be tested on rancher-backup:`2.0.0+up2.0.0-rc2` in rancher:`master-head`

**Comment by sowmyav27** [comment]
Will be tested as part of this issue - https://github.com/rancher/rancher/issues/33428
