### ISSUE TITLE
when creating a backup with S3 and specifying a folder with a trailing `/` instead creates a folder named `/` 

### ISSUE THREAD

**Issue by slickwarren** [rancher/backup-restore-operator#125]
on master-head (4d1840056b02e390c29a9497abffc840c1de3b28) 
repro steps:
* install rancher backups
* using S3, specify the folder name in your bucket with a trailing `/` i.e. `rancher-backups/`
* create a backup of your cluster

![Screen Shot 2021-06-21 at 9 34 14 AM](https://user-images.githubusercontent.com/16691014/122809117-8c846380-d282-11eb-861c-1a3d42ec173c.png)

Result:
* in S3, a folder in `rancher-backups` is created named `/`. The backup is stored there

![Screen Shot 2021-06-21 at 9 33 10 AM](https://user-images.githubusercontent.com/16691014/122809120-8db59080-d282-11eb-8f2b-24a9ae2ba0f5.png)

**Comment by jiaqiluo** [comment]
can be tested in rancher-backup chart 2.0.0+up2.0.0-rc3

**Comment by anupama2501** [comment]
Verified on master-head b6bcfad

- On an HA server installed rancher backup `rancher-backup:2.0.0+up2.0.0-rc4`
- Following config is provided in the S3 compatible object 

<img width="300" alt="Screen Shot 2021-07-21 at 3 42 24 PM" src="https://user-images.githubusercontent.com/38144301/126569136-748952ca-999a-4aa6-b441-11d78f6c2012.png">
 
- Verified folder `/` is not created and the backup zip file is saved in the folder provided in the config
