### ISSUE TITLE
[Backport] when creating a backup with S3 and specifying a folder with a trailing / instead creates a folder named /

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/backup-restore-operator#128]
backport of https://github.com/rancher/backup-restore-operator/issues/125

**Comment by jiaqiluo** [comment]
can be tested in rancher-chart version 1.2.0-rc3

**Comment by anupama2501** [comment]
Verified on v2.5-head 0713103

- Installed rancher backup `rancher-backup:1.2.0-rc3`
- Created a backup by providing the following config and verified no trailing `/` is created,

<img width="400" alt="Screen Shot 2021-08-04 at 10 35 35 AM" src="https://user-images.githubusercontent.com/38144301/128227814-2e28c5f6-91b0-4408-8cf9-082638180369.png">
