### ISSUE TITLE
Upgrade the client-go package 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/backup-restore-operator#131]
Upgrade the client-go package to [the current latest v0.21.2 ](https://github.com/kubernetes/client-go/releases/tag/v0.21.2)

**Comment by jiaqiluo** [comment]
available in rancher-backup chart `2.0.0+up2.0.0-rc4` and above 

Only need to validate that the chart continues working normally.

**Comment by deniseschannon** [comment]
No need to do a separate validation as backup and restore will automatically with other issues and release validation.
