### ISSUE TITLE
Restore fails if backup contains a resource that is currently being deleted

### ISSUE THREAD

**Issue by bashofmann** [rancher/backup-restore-operator#188]
The restore of a backup fails if the backup tar.gz contains a resource that is currently being deleted (has `metadata.deletionGracePeriodSeconds` set).
This can easily happen if a finalizer is blocking the deleting of an object while the backup is being terminated.

When trying to restore the backup, you get this error:

```
ERRO[2022/01/28 16:07:45] Error restoring namespaced resources [error restoring rancher-k3s-upgrader of type project.cattle.io/v3, Resource=apps: restoreResource: err updating resource App.project.cattle.io "rancher-k3s-upgrader" is invalid: metadata.deletionGracePeriodSeconds: Invalid value: 0: field is immutable]
```

One way to reproduce:

* Create a resource that is included in the default rancher resourceset, e.g. a GitRepo
* Manually edit the yaml of this resource and add a custom finalizer to it
* Delete the resource. The resource should be now stuck in terminating because of the custom finalizer
* Create a backup
* Try to restore the backup in a new cluster

**Comment by superseb** [comment]
@bashofmann Can you provide more info on this issue so it can be used to reproduce and validate if a fix is the right approach?

- Version information of backup-restore-operator used and Kubernetes distro and version used.
- You state it is restored in a new cluster but the error shows `updating resource`, can you share more exact steps on reproducing and possibly the archive so it can be used to reproduce/test?

**Comment by bashofmann** [comment]
Rancher 2.6.3
rancher-backup 2.1.0
Kubernetes version source cluster: v1.21.9+rke2r1
Kubernetes version target cluster: v1.21.9+rke2r1

The log message above is coming from the pod that runs the restore process. The pod is trying to restore in a loop and always fails to restore the resource that was already "in deletion" while the backup was created.

So as soon as the backup contains a resource that was stuck  in deletion because of a finalizer when the backup was created, the restore fails. I can reproduce it with the steps above.
Of course in practice no one would just add a custom finalizer. But it could be that a backup was created while a cluster is being deleted. Since it can take some time until a finalizer is finished and the resource is removed, or a finalizer is unable to finish and stuck, this scenario is not that unlikely. 

A fix could be to not include resources with deletionGracePeriodSeconds set in the backup archive.

**Comment by braunsonm** [comment]
We are running into this as well. Is there any work around? We didn't add any of our own finalizers but happened to have some resources stuck in this state.

**Comment by bashofmann** [comment]
Sounds good. The only thing I'm unsure about if `deletionGracePeriodSecond` is the only immutable field or if it also affects `deletionTimestamp`.
