### ISSUE TITLE
RFE: Update the name for the backup file when it's encrypted

### ISSUE THREAD

**Issue by maggieliu** [rancher/backup-restore-operator#21]
If the backend named encrypted backups with an e.g. .encrypted suffix, then the UI could look at the filename entered and definitively tell you that you need to have the encryption config instead of having the user guess from the warning message.

**Comment by mrajashree** [comment]
available with the latest commit https://github.com/mrajashree/charts/tree/backup-restore-sep-charts
it also includes the latest tag in values.yaml
The backup filename will have suffix ".enc" if its contents are encrypted

**Comment by sowmyav27** [comment]
**On master-head - commit id: `76c26fb0`** 

- backup-restore image:
```
  repository: rancher/backup-restore-operator
  tag: v0.0.1-rc10
```
- Create a backup CR with encryption set `encryptionConfigSecretName: test-encryptionconfig`
- filename in the deployed backup CR is: `filename: b1-encrypted-46d6e18b-2491-4f09-b2d3-23b59c58827f-2020-09-08T18#01#39Z.tar.gz.enc`
<img width="1670" alt="Screen Shot 2020-09-08 at 11 01 54 AM" src="https://user-images.githubusercontent.com/26032343/92511983-f257a100-f1c2-11ea-9f6e-f58293519b99.png">
