### ISSUE TITLE
Backup restore operator does not backup rkecontrolplanes.rke.cattle.io

### ISSUE THREAD

**Issue by braunsonm** [rancher/backup-restore-operator#210]
After restoring a Rancher cluster with RKE2 child clusters, the clusters enter an error state with `rkecontrolplanes.rke.cattle.io "test" not found`

It seems this might be be backed up as part of the default `ResourceSet`

**Comment by superseb** [comment]
What version did you use for creating the backup?

**Comment by braunsonm** [comment]
Sorry that would have been good info to add @superseb 

Chart version 2.0.1
Kubernetes version 1.21

**Comment by superseb** [comment]
While I reproduce, can you check if the archive contains the resource?

**Comment by superseb** [comment]
Any debug logs from Rancher from that time that you can share? And maybe also the backup-restore-operator logs

**Comment by braunsonm** [comment]
I don't have the logs anymore unfortunately, but the backup completed successfully.

**Comment by superseb** [comment]
@braunsonm Did you run into this again?

**Comment by braunsonm** [comment]
I haven't had to restore since

**Comment by braunsonm** [comment]
Bump still an issue afaik

**Comment by superseb** [comment]
I just tested this on latest and the archive contains `rkecontrolplanes.rke.cattle.io` and the CRs get restored. We need a reproducer for this.
