### ISSUE TITLE
Make debug and trace loglevels configurable in chart

### ISSUE THREAD

**Issue by superseb** [rancher/backup-restore-operator#217]
Debug and trace flags were added in https://github.com/rancher/backup-restore-operator/pull/204/files#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261R61, should be configurable in chart.

Similar to `rancher/rancher`: https://github.com/rancher/rancher/blob/v2.6.4/chart/values.yaml#L35

**Comment by eliyamlevy** [comment]
PR: https://github.com/rancher/backup-restore-operator/pull/227
