### ISSUE TITLE
User has access when user is removed from cluster

### ISSUE THREAD

**Issue by sowmyav27** [rancher/backup-restore-operator#25]
**On master-head - commit id: `4911f8b`**

**Steps:**

- On a HA setup (RKE cluster) Deploy a custom cluster (downstream)
- Add user u1 as cluster owner of the custom cluster
- Take a backup b1 using backup restore operator.
- Remove the cluster owner association of the user from the cluster
- take a backup b2
- restore to backup b1. (on the same HA rancher setup)
- When the rancher server has come up, delete the associating of user u1 as cluster owner of the cluster.
- Login as user u1
- User can list the cluster and can add namespaces/perform actions on the cluster like enable monitoring/run cis scan

**Expected**
User should NOT have access to the cluster after his association has been removed

**Comment by mrajashree** [comment]
Seems related to https://github.com/rancher/rancher/issues/28370

**Comment by sowmyav27** [comment]
**On master head - commit id: `ad014cdc8e`**

- On a HA setup (RKE cluster) Deploy a custom cluster (downstream)
- Add user u1 as cluster owner of the custom cluster
- Take a backup b1 using backup restore operator.
- Remove the cluster owner association of the user from the cluster
- take a backup b2
- restore to backup b1. (on the same HA rancher setup)
- When the rancher server has come up, delete the associating of user u1 as cluster owner of the cluster.
- Login as user u1
- User CANNOT list the cluster anymore
