### ISSUE TITLE
Restore Rancher from K3s to RKE leaves the local cluster stuck in Upgrading

### ISSUE THREAD

**Issue by linyinli** [rancher/backup-restore-operator#252]
Hi,
I used Rancher Backup to restore Rancher from K3s to RKE, but it leaves the local cluster stuck in Upgrading.

Steps to reproduce:
- Rancher cluster running on K3s
- Backup to PV
- Create  a new RKE cluster
- Restore backup to RKE cluster (prune: false)

I found that local cluster is still configured as K3s provider and is stuck in Cluster is being upgraded.

![image](https://user-images.githubusercontent.com/42955482/176004948-0a1aec8c-3c9a-4bd0-949b-7a33de9566ce.png)

![image](https://user-images.githubusercontent.com/42955482/176004892-6ef5cf75-42f5-4bb2-9f82-ad9fb1d52683.png)

As a workaround, I edited the local cluster.management.cattle.io CRD:

- Removed k3sConfig
- Removed Upgraded status
- Changed driver from k3s to imported
- Changed provider from k3s to rke

I have no idea whether this breaks something, any other solution here?

K3s: 1.20.15
RKE: 1.20.15
Rancher Backup: v2.1.2

**Comment by superseb** [comment]
This should include investigating if we can just drop the local cluster resource as it seems we don't need to restore anything for it (it is there when we restore) and we dont want to create a conflict by restoring things.
