### ISSUE TITLE
bug Upgrade 2.1.2 on RKE2

### ISSUE THREAD

**Issue by Giancarlo1974** [rancher/backup-restore-operator#260]
I have Rancher 2.6.5 installed on RKE2 v1.23.6+rke2r1

When try to upgrade rancher-backup  chart
1.2.100+up1.2.1 > 2.1.2

i got this error

`helm upgrade --history-max=5 --install=true --namespace=cattle-resources-system --timeout=10m0s --values=/home/shell/helm/values-rancher-backup-crd-2.1.2.yaml --version=2.1.2 --wait=true rancher-backup-crd /home/shell/helm/rancher-backup-crd-2.1.2.tgz

--
Tue, Jul 26 2022 5:33:44 pm | Error: UPGRADE FAILED: current release manifest contains removed kubernetes api(s) for this kubernetes version and it is therefore unable to build the kubernetes objects for performing the diff. error from kubernetes: unable to recognize "": **no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"**
`

**Comment by superseb** [comment]
Where did you upgrade from? This is most likely related to https://github.com/rancher/rancher/issues/34154 but would have been avoided if you upgraded one patch version at a time plus upgraded the apps installed after each rancher upgrade.

**Comment by Giancarlo1974** [comment]
I think I was able to fix it by completely uninstalling Rancher Backup Operator
