### ISSUE TITLE
Allow passing the imagePullSecrets value

### ISSUE THREAD

**Issue by jlunaq** [rancher/backup-restore-operator#264]
Hello, is there any plan to support this? I need to pass the secret to be able to authenticate with a docker private docker and pull the image. Thanks

**Comment by superseb** [comment]
@jlunaq sure, this is just a chart addition right? If you want to make a PR for it, go for it. Else we will look at it.

**Comment by jlunaq** [comment]
Hi @superseb, thanks for adding this feature, I see it's already merged to main, in which version is this going to be available? Currently I'm using 2.1.3

**Comment by superseb** [comment]
@jlunaq It will be officially released in v2.1.4 which is planned for v2.6.9. You can test if it works by using v2.1.4-rc1 (not in production obviously)

**Comment by jlunaq** [comment]
Great, I'm currently using Rancher v2.6.8 in a sandbox cluster, for sure I can test v2.1.4-rc1. Thank you

**Comment by jlunaq** [comment]
Hi @superseb, I cannot pull v2.1.4-rc1 from the charts.rancher.io repository, can you please share the one I should use instead?

**Comment by eliyamlevy** [comment]
HI @jlunaq I you should be using https://git.rancher.io/charts as your repository, the key is to change the branch from release-v2.6 to dev-v2.6 and you'll see it. Although I'd add it as a second repo instead of replacing your default rancher one.

**Comment by jlunaq** [comment]
@eliyamlevy Do you have an example using helm?

**Comment by eliyamlevy** [comment]
I do not, this is accomplishable from the rancher ui. As far as choosing branches on a helm repository through the cli I don't think that's supported. What you can do is clone the rancher/charts git repo and checkout the dev-v2.6 branch. From there you can install the latest charts through your terminal with helm.

**Comment by ronhorton** [comment]
**Pass** verified in `2.6.9-rc4`
1. installing backup-restore-operator
2. edited yaml at install to pass in imagepullsecrets value
3. install completed with no errors
