### ISSUE TITLE
unable to restore rancher using backup operator with local-path

### ISSUE THREAD

**Issue by nitin992vij** [rancher/backup-restore-operator#279]
Hi,

Following steps that I performed to restore my rancher local cluster to an old state. 
- Installed Rancher on k3s single node cluster 
- Installed Rancher backup operator in the local cluster with local-path storage class
- Imported another k3s cluster in Rancher
- Took the backup of local cluster with default storage (local-path)
- Deleted the imported k3s cluster
- Restored the backup that was taken before deleting downstream imported cluster.  

Rancher Application took some time to start and after some time, the downstream imported cluster is visible but with unavailable status and even the rancher pods are restarting from time to time.
![image](https://user-images.githubusercontent.com/45073684/199662570-0d8a12b0-6361-4c2e-ab5d-9ed3706a7b67.png)

**Comment by MKlimuszka** [comment]
@nitin992vij , we'll need some more info to triage this.

    Rancher version of local and any downstream clusters
    OS of local and any downstream clusters

**Comment by nitin992vij** [comment]
Rancher Version: V2.6.8
OS version of Local Cluster: Red Hat Enterprise Linux 8.4

**Comment by eliyamlevy** [comment]
It seems you are doing an "in-place" restoration. Did you run the restore with prune enabled?

**Comment by eliyamlevy** [comment]
After some investigation I've come to this conclusion:

Some resources have external results produced upon deletion, like downstream clusters. As of yet deleting a downstream cluster and restoring the cluster resource on the local cluster does NOT cause rancher to “re-provision” said cluster. Depending on the resource, restoring may not fully bring back the resource to an available state.

The corner case of "restoring a deleted cluster" has come up a few times and is not a supported feature. When it comes to downstream clusters, whether provisioned or imported, deleting them causes a series of cleanup tasks which essentially don't allow the user to restore the deleted clusters. Provisioned clusters will have their nodes and rancher related provisioning resources destroyed, and imported cluster will likely have their rancher agents and other resources/services related to registration with a local cluster destroyed as well. This is something which can become a feature request should the need to support it come up.

NOTE: Trying to delete and restore a downstream cluster can lead to a variety of issues with rancher, rancher-backups, rancher-webhook, fleet, and more. It is not recommended to do this.

**Comment by txj-xyz** [comment]
Is there any official way to skip the cluster that was deleted in the restore or do we need to manually delete the resources from the `tar.gz` of the backup?
