### ISSUE TITLE
unable to restore rancher using backup operator with minio

### ISSUE THREAD

**Issue by nitin992vij** [rancher/backup-restore-operator#280]
Hi,

Following steps that I performed to restore my rancher local cluster to an old state.

- Installed Rancher on k3s single node cluster
- Installed Rancher backup operator in the local cluster with minio
- Imported another k3s cluster in Rancher
- Took the backup of local cluster with minio
- Deleted the imported k3s cluster
- Restored the backup that was taken before deleting downstream imported cluster.

Rancher Application took some time to start and after some time, the downstream imported cluster is visible but with unavailable status.
![image](https://user-images.githubusercontent.com/45073684/199723396-64fc34ac-1f59-47cf-8d1a-3e8d72545614.png)

**Comment by MKlimuszka** [comment]
@nitin992vij , we'll need some more info to triage this.

- Rancher version
- OS of local and any downstream clusters

**Comment by nitin992vij** [comment]
Rancher Version: V2.6.8
OS version: Red Hat Enterprise Linux 8.4

**Comment by eliyamlevy** [comment]
https://github.com/rancher/backup-restore-operator/issues/279#issuecomment-1496303937

**Comment by eliyamlevy** [comment]
Please see my comment here: https://github.com/rancher/backup-restore-operator/issues/279#issuecomment-1585072910
