### ISSUE TITLE
Support backup/restore installation on hardened cluster

### ISSUE THREAD

**Issue by maggieliu** [rancher/backup-restore-operator#29]
Support backup/restore installs on hardened cluster

**Comment by cbron** [comment]
This is a requirement for 2.6.

**Comment by jiaqiluo** [comment]
can be tested on rancher-backup:`2.0.0+up2.0.0-rc2` in rancher:`master-head`

**Comment by sowmyav27** [comment]
**On master-head commit id: `d44698d` and backup version `rancher-backup:2.0.0+up2.0.0-rc2`**

- Able to deploy and take a backup on the local cluster - RKE1 which is hardened using [this](https://rancher.com/docs/rancher/v2.x/en/security/rancher-2.5/1.6-hardening-2.5/) doc
