### ISSUE TITLE
Finalize default rancher-resource-set

### ISSUE THREAD

**Issue by mrajashree** [rancher/backup-restore-operator#30]
- [x] Resources for catalog.cattle.io (check if we need only clusterrepos.catalog.cattle.io)

- [x] eks-operator

- [x] rancher-operator

- [x] fleet

- [x] Exclude helm secrets

**Comment by mrajashree** [comment]
Based on offline discussion, rancher's default resource-set for 2.5 should only have:

- [x] Resources for catalog.cattle.io (check if we need only clusterrepos.catalog.cattle.io)

- [x] eks-operator

- [x] Exclude helm secrets

**Comment by sowmyav27** [comment]
Reopening the issue because of this issue https://github.com/rancher/backup-restore-operator/issues/44#issuecomment-701144908

**Comment by mrajashree** [comment]
https://github.com/rancher/backup-restore-operator/issues/44#issuecomment-701188611

**Comment by sowmyav27** [comment]
**On master-head - commit id: `2ae933e08`**

- Used helm 3.2.4 version to install Rancher HA setup.
- Take backup b1
- Restore to a new Rancher setup where helm version is 3.2.4
- Install worked using `rancher install` instead. 
- Able to restore successfully and install rancher.
- Take another backup b2 in the new rancher setup. Cluster and users from previous rancher are available. User is able to access/edit the cluster that the user is owner of. 
- Fleet and rancher-operator are NOT available in the resourceset.
