### ISSUE TITLE
[2.7] Update Wrangler Go Package

### ISSUE THREAD

**Issue by eliyamlevy** [rancher/backup-restore-operator#306]
**Rancher Server Setup**
- Rancher version: `v2.7`

**Describe the bug**
We need to update to wrangler `v1.0.2` for a cve patch. This is for `v2.7` so must go into `release/v3.0`.

## Testing

Since this is just updating packages/modules/images the general functionality should be tested. However there should be a specific round of testing focused on the encryption feature. Since this wrangler update led to having to update how the encryption transformer overrides are loaded.

**Comment by eliyamlevy** [comment]
It seems that wrangler `v1.x`  line uses the k8s `v1.25` client. This means until we create a strictly `v1.25` release line for backup-restore-operator, it cannot be updated past the `v0.8.x` line of wrangler.

**Comment by prachidamle** [comment]
@eliyamlevy Can this ticket be moved to-test? Can we add tests for this ticket? Also what testcases should QA ensure to cover?

**Comment by eliyamlevy** [comment]
@prachidamle Just cut new RC to test a wave of updated packages and consumed upstream elements. Working on charts pr now.

**Comment by eliyamlevy** [comment]
New pr open

**Comment by ronhorton** [comment]
**Pass** verified in rancher `v2.7-head commit iD b5627bd`
1. installed rancher-backups
2. created backup with encryption
3. backup completed
4. restored successfully from backup taken in step 3
