### ISSUE TITLE
Add ResourceSets for v2 apps (monitoring, istio, logging, cis)

### ISSUE THREAD

**Issue by sowmyav27** [rancher/backup-restore-operator#31]
On master-head - `53cf961efce` and app tag - rc12

rancher-resource-set is missing v2 apps. - https://github.com/rancher/backup-restore-operator/issues/6#issuecomment-689197005

**Comment by mrajashree** [comment]
Rancher-resource-set won't contain all resources for v2 apps. We will have to create separate resourceSets for each.

**Comment by maggieliu** [comment]
This is post 2.5.
