### ISSUE TITLE
Avoid restoring system cluster resources

### ISSUE THREAD

**Issue by rverchere** [rancher/backup-restore-operator#317]
**Rancher Server Setup**
- Rancher version: 2.6.10
- Installation option (Docker install/Helm Chart): Helm
- Kubernetes Version and Engine: 1.23.14, managed

**Describe the bug**
When restoring a rancher to a cluster which has not the same underlying components (i.e. from rke1 to managed one - gcp, aws, whatever), the restoring tool restores a LOT of resources, including ClusterRoles `system:*` which should not be modified.

This leads to some unexpected behaviour on my side : metric-server does not work anymore, default SA cannot resolve DNS, ...

**To Reproduce**
1. Restore a cluster
2. Check `system:*` ClusterRoles, they are modified

**Expected behavior**
1. Restore a cluster
2. Check `system:*` ClusterRoles, they should not be modified

**Workaround**
1. Get system: ressources from another "clean" cluster, and apply them

**Comment by AlexisDucastel** [comment]
Totally agree with @rverchere ! Modifying cluster system roles is usually not a good idea.

**Comment by fredleger** [comment]
Or at least should be an option IMHO

**Comment by MKlimuszka** [comment]
I will have to check whether or not this use case is supported. For now I am marking it as a feature request.

**Comment by nickwsuse** [comment]
Verified on v2.7.12-alpha2 ✅ 
----
Backups and restores are working as expected with this change.

In-Place Restore: ✅ 
Rollback an upgrade on the same Rancher Server: ✅ 
Migration from RKE1 to RKE2 local cluster: ✅
