### ISSUE TITLE
rancher-charts repo doesn't have latest version?

### ISSUE THREAD

**Issue by ajchiarello** [rancher/backup-restore-operator#318]
I'm trying to install the latest release (3.1.0) using the instructions in the README, but it appears that the latest version in https://charts.rancher.io is 2.1.5?

**Comment by MKlimuszka** [comment]
We just released 3.1.0, and the associated Rancher release 2.7.2. Check again to see if you are still having this problem. If you are, please comment with more info on your environment and how you are trying to install the chart.

**Comment by ajchiarello** [comment]
I'm following the instructions in the [Quickstart](https://github.com/rancher/backup-restore-operator#quickstart) section, which says to use helm to add the rancher-charts repo and then install the rancher-backup-crd and rancher-backup charts. When I try to do that, the version that installs is 2.1.5, which is also the version that shows when I run a `helm search repo rancher-backup`. I've updated to rancher 2.7.2, but that has not changed this output. Are the instructions in the Quickstart section of the README out of date?

**Comment by eliyamlevy** [comment]
Please give us more information on your setup i.e. cluster provisioning, hosting, node os, k8s version, so on.
