### ISSUE TITLE
Charts in the local cluster are not displayed after a restore 

### ISSUE THREAD

**Issue by soumyalj** [rancher/backup-restore-operator#32]
Version: master-head(master-33f755f1809e5cb14b7749af462be8b8db240278-head)

Steps:
1. Create a HA setup using RKE nodes. 
2. On the local cluster, add a repo https://github.com/rancher/charts 
3. Create a downstream DO cluster and enable monitoring and istio
4. Create another custom cluster and deploy monitoring
5. Create an EKS clsuter
6. Deploy BackupRestoreOperator Chart in the local cluster and take a backup bkp1
7. Restore to bkp1 on a new RKE cluster using the below steps:
```
a. Install the backup-restore-operator chart on the new cluster using Helm CLI
b. helm repo add rancherchart https://charts.rancher.io
c. helm repo update
d. helm install backup-restore-operator-crd rancherchart/backup-restore-operator-crd -n cattle-resources-system --create-namespace
e. helm install backup-restore-operator rancherchart/backup-restore-operator -n cattle-resources-system
f. Restore from backup using a restore CR and prune must be set to false. 
g. If using certificates issued by Rancher’s generated CA, follow steps to install cert-manager from rancher HA install docs
h. Upgrade rancher release. If on the previous cluster rancher deployment was scaled down, you can also set the right scale (3) through the upgrade command

helm upgrade rancher rancher-alpha/rancher --version 2.5.0-alpha1 --namespace cattle-system 
--set hostname=<same hostname as first rancher server> --set rancherImageTag=master-head 
```

After restore, the charts in the local cluster are not displayed. The repositories are displayed correctly
![Screen Shot 2020-09-16 at 10 13 25 PM](https://user-images.githubusercontent.com/18536626/93424546-15dab580-f86d-11ea-9427-f9e4e1cf1fe3.png)

![Screen Shot 2020-09-16 at 10 19 58 PM](https://user-images.githubusercontent.com/18536626/93424577-23903b00-f86d-11ea-99f3-ef8fb87e5e9e.png)

**Note:**
Charts in the downstream clusters are displayed as expected.
Monitoring and istio are enabled and running in the downstream clusters and EKS cluster is also running after restore.

**Comment by mrajashree** [comment]
@soumyalj @sowmyav27 so we can close out this issue then?https://github.com/rancher/backup-restore-operator/issues/6

**Comment by sowmyav27** [comment]
As part of testing this issue, verify **only** `clusterrepos.catalog.cattle.io` is available in the default rancher-resource-set.

**Comment by soumyalj** [comment]
Tested with the steps above with restore to master-head(8fd81a9b46847317a)

After restore, one of the charts in the local cluster is missing.

![Screen Shot 2020-09-18 at 5 15 26 PM](https://user-images.githubusercontent.com/18536626/93654543-ee056200-f9d2-11ea-9b16-58ab67712b9f.png)

The repository exists:
![Screen Shot 2020-09-18 at 5 18 45 PM](https://user-images.githubusercontent.com/18536626/93654561-0e352100-f9d3-11ea-8ca0-5810cbdac553.png)

**Comment by mrajashree** [comment]
that's weird, worked when I was testing, I'll look at the setpu

**Comment by mrajashree** [comment]
The test setup didn't seem to use the right rancher-resource-set. I'm assigning it over to test, can you share the resource-set on your setup before the backup? @soumyalj

**Comment by sowmyav27** [comment]
**On master-head - commit id: `f8bad24e`**

- On a restore , custom repo and the repos and charts were available
<img width="1200" alt="Screen Shot 2020-09-18 at 10 25 03 PM" src="https://user-images.githubusercontent.com/26032343/93659772-d1325400-f9fd-11ea-8016-61b1ddcabc83.png">

**Comment by soumyalj** [comment]
Verified with the steps above with restore to master-head(f8bad24ea762823ec0305a)

After restore, charts in the local cluster are displayed correctly. 

![Screen Shot 2020-09-18 at 11 14 48 PM](https://user-images.githubusercontent.com/18536626/93660530-c8914c00-fa04-11ea-9f80-9a160f0c178c.png)

Repositories are also displayed correctly.

![Screen Shot 2020-09-18 at 11 16 43 PM](https://user-images.githubusercontent.com/18536626/93660551-07bf9d00-fa05-11ea-8f80-6bb0040bf959.png)

**Comment by sowmyav27** [comment]
Resourceset on master-head - commit id `f1a410a97` has
```
- apiVersion: apiextensions.k8s.io/v1beta1
  kindsRegexp: .
  resourceNameRegexp: management.cattle.io$|project.cattle.io$|catalog.cattle.io$|eks.cattle.io$|resources.cattle.io$
- apiVersion: catalog.cattle.io/v1
  kindsRegexp: ^clusterrepos$
```
