### ISSUE TITLE
Make sure backup/restore passes CIS hardened profile scan

### ISSUE THREAD

**Issue by maggieliu** [rancher/backup-restore-operator#34]

**Comment by jiaqiluo** [comment]
This will be covered by [supporting backup/restore installation on hardened cluster ](https://github.com/rancher/backup-restore-operator/issues/29)

**Comment by jiaqiluo** [comment]
can be tested on rancher-backup:`2.0.0+up2.0.0-rc2` in rancher:`master-head`

**Comment by sowmyav27** [comment]
Blocked because of https://github.com/rancher/cis-operator/issues/98

**Comment by sowmyav27** [comment]
**On master-head commit id: `9e0d1b2`**

No additional CIS tests fail on a Hardened local RKE1 cluster after installing rancher backups.
