### ISSUE TITLE
Add initial Renovate configuration

### ISSUE THREAD

**Issue by eliyamlevy** [rancher/backup-restore-operator#350]
Add initial Renovate configuration, includes Renovate configuration file and GitHub Actions workflow. This automatically created PR has been initiated by @eliyamlevy

**Comment by prachidamle** [comment]
@macedogm Do we need a sign off on the renovate bot tickets from the security team? Is there anything for QA to test so that we can close this ticket?

**Comment by macedogm** [comment]
@prachidamle no, there is nothing needed from Security or QA regarding this. After the PR is merged, Renovate should start opening update PRs.

**Comment by macedogm** [comment]
By the way, the PRs are already opened (since 2 weeks ago) - https://github.com/rancher/backup-restore-operator/pulls/app%2Frenovate-rancher.

**Comment by prachidamle** [comment]
Thanks for the info @macedogm!

**Comment by ronhorton** [comment]
closing. confirmed no QA needed.
