### ISSUE TITLE
restore is not working: Error restoring CRDs restoreCRDs: restoreResource: err creating resource the server could not find the requested resource

### ISSUE THREAD

**Issue by jdambly-ns** [rancher/backup-restore-operator#362]
**Rancher Server Setup**
- Rancher version: 2.6.11
- Installation option (Docker install/Helm Chart): helm
- Kubernetes Version and Engine: 1.24.x GKE

**Describe the bug**
restore is not working

**Screenshots**
INFO[2023/05/24 16:39:03] Processing Restore CR restore-migration
INFO[2023/05/24 16:39:03] Restoring from backup local-iad0-146693fe-4556-4a67-b26b-c9746049ce5f-2023-05-24T15-54-30Z.tar.gz
INFO[2023/05/24 16:39:03] invoking set s3 service client                s3-accessKey=29982bc0bbdf47989013c4b5f312ec70 s3-bucketName=rancher-backup-container s3-endpoint="cloud.nc1.iad0.netskope.com:8080" s3-endpoint-ca= s3-folder=local-iad0 s3-region=
INFO[2023/05/24 16:39:04] Temporary location of backup file from s3: /tmp/local-iad0-146693fe-4556-4a67-b26b-c9746049ce5f-2023-05-24T15-54-30Z.tar.gz
INFO[2023/05/24 16:39:04] Successfully downloaded backup file [local-iad0/local-iad0-146693fe-4556-4a67-b26b-c9746049ce5f-2023-05-24T15-54-30Z.tar.gz] from bucket [rancher-backup-container]
INFO[2023/05/24 16:39:20] Processing controllerRef apps/v1/deployments/rancher
INFO[2023/05/24 16:39:20] Scaling down controllerRef apps/v1/deployments/rancher to 0
INFO[2023/05/24 16:39:20] Starting to restore CRDs for restore CR restore-migration
INFO[2023/05/24 16:39:20] restoreResource: Restoring features.management.cattle.io of type apiextensions.k8s.io/v1beta1, Resource=customresourcedefinitions
INFO[2023/05/24 16:39:20] Processing controllerRef apps/v1/deployments/rancher
INFO[2023/05/24 16:39:20] Scaling up controllerRef apps/v1/deployments/rancher to 0
ERRO[2023/05/24 16:39:20] Error restoring CRDs restoreCRDs: restoreResource: err creating resource the server could not find the requested resource
ERRO[2023/05/24 16:39:20] error syncing 'restore-migration': handler restore: error restoring CRDs, check logs for exact error, requeuing

what logs is this talking about? I don't see any other lets and there are no events

(⎈ |gke_ops-testbed_us-west1_rancher-prime-iad0:cattle-resources-system)➜  ~ k get events
W0524 09:42:09.363972   88409 gcp.go:119] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.26+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
No resources found in cattle-resources-system namespace.
(⎈ |gke_ops-testbed_us-west1_rancher-prime-iad0:cattle-resources-system)➜  ~

please help

**Comment by MKlimuszka** [comment]
Closing as stale. Reopen with new info if needed. It's recommended to upgrade away from 2.6.x.
