### ISSUE TITLE
Backup fails due to retention enforcement on a versioned AWS S3 bucket.

### ISSUE THREAD

**Issue by rbutcher** [rancher/backup-restore-operator#366]
**Rancher Server Setup**
- Rancher version: 2.7.4
- Installation option (Docker install/Helm Chart): Helm Chart
- Kubernetes Version and Engine: EKS v1.25

**Describe the bug**
I have the backup-operator configured to back up to a versioned AWS S3 bucket. When the operator attempts to enforce the retention policy during a backup, removal of the object fails because the VersionId is not provided with the remove request. This causes the backup to fail and retry every few minutes, constantly writing new backup objects into the bucket.

**To Reproduce**
1. Configure a backup to a versioned AWS S3 bucket with a retention count.
2. Allow the first backups up to the retention count successfully complete.
3. Observe next backup will fail due to being unable to delete a versioned object without a VersionId.

**Expected behavior**
The RemoveObject call should specify both the object Key and VersionId to support removing an object from a versioned bucket. 

**Screenshots**
I recently migrated to a new Rancher instance, so, I cannot provide screenshots of the backup configuration. I had it configured to take backups nightly at 3am (local). But I still have the bucket that backup filled up. You can see it retires every ~3 minutes or so.
![image](https://github.com/rancher/backup-restore-operator/assets/7253688/c3299fbc-6ce9-4117-9b71-a6a4781422a7)

**Additional context**
I believe the issue could be addressed by adding the VersionId to the RemoveObjectOptions on [this line](https://github.com/rancher/backup-restore-operator/blob/9cd449e7932ec41f639bcc2d56161dd611d58117/pkg/controllers/backup/retention.go#L149) but have not thought it all the way through. It could be that the call would need to have more data or the way filtering works would have to be updated. I will fiddle with this in a fork to try to resolve my issue meanwhile.

**Comment by todeb** [comment]
hello, @rbutcher I'm having exact same issue, did you manage to solve this?
