### ISSUE TITLE
Chart changes

### ISSUE THREAD

**Issue by mrajashree** [rancher/backup-restore-operator#37]
- [x] Rename chart to rancher-backup instead of backup-restore-operator. We want to present this chart more as a tool for backing up and restoring rancher in 2.5 than presenting it as a generic utility

**Comment by sowmyav27** [comment]
On master-head - commit id: `9de5a8509`
Reopening as the older charts isnt deleted

**Comment by sowmyav27** [comment]
**On master-head - commit id: `ec04f787`**

Older charts are deleted.
rancher-backups is available
<img width="1675" alt="Screen Shot 2020-09-28 at 10 54 54 AM" src="https://user-images.githubusercontent.com/26032343/94468829-e5065480-0179-11eb-973f-79a147570745.png">
