### ISSUE TITLE
Not able to change storage locations from storage class 1 to storage class 2 while upgrading the rancher-backup app

### ISSUE THREAD

**Issue by sowmyav27** [rancher/backup-restore-operator#39]
**On master-head - commit id: `27000be7`**

- Install backup storage. Using the default storage class (gp2). App is installed successfully. User is able to take  a backup
- Upgrade the app --> change it to another storage class (st1) and hit save.
- Error seen:

```
helm upgrade --history-max=5 --install=true --namespace=cattle-resources-system --timeout=10m0s --values=/home/shell/helm/values-rancher-backup-0.1.0.yaml --version=0.1.0 --wait=true rancher-backup /home/shell/helm/rancher-backup-0.1.0.tgz
checking 5 resources for changes
Looks like there are no changes for ServiceAccount "rancher-backup"
error updating the resource "rancher-backup":
cannot patch "rancher-backup" with kind PersistentVolumeClaim: PersistentVolumeClaim "rancher-backup" is invalid: spec: Forbidden: is immutable after creation except resources.requests for bound claims
Looks like there are no changes for ClusterRoleBinding "rancher-backup"
Looks like there are no changes for Deployment "rancher-backup"
Error: UPGRADE FAILED: cannot patch "rancher-backup" with kind PersistentVolumeClaim: PersistentVolumeClaim "rancher-backup" is invalid: spec: Forbidden: is immutable after creation except resources.requests for bound claims
```
- This is expected because it is trying to create another PVC when it is already bound.
- Delete the PVC manually, and delete the deployment rancher-backup and then try an upgrade using storage class st1 and it worked.

**Comment by mrajashree** [comment]
The PVC name is same as the chart name. This can be fixed by using release name as PVC name. And an annotation in the deployment to trigger creation of new pod

**Comment by sowmyav27** [comment]
**On master-head commit id: `ec04f7878`**

- Install backup storage. Using the default storage class (gp2). App is installed successfully. User is able to take a backup 
- Upgrade the app --> change it to another storage class (st1) and hit save.
- App deploys successfully
- A new PVC is created with different name `rancher-backup-2`
