### ISSUE TITLE
Incorrect deduplication logic due to invalid pointer address

### ISSUE THREAD

**Issue by mallardduck** [rancher/backup-restore-operator#408]
Those code here, and the similar instance of it that are in this file, creates an invalid pointer situation.
https://github.com/rancher/backup-restore-operator/blob/2d3421efda1032fcb2d14fd8853e104420f2f6f2/pkg/resourcesets/collector.go#L246
https://github.com/rancher/backup-restore-operator/blob/2d3421efda1032fcb2d14fd8853e104420f2f6f2/pkg/resourcesets/collector.go#L258

As the code is scoped to the for loop block the `resObj` is a single variable being reset each iteration of the loop. This means that each time we attempt to "reference the pointer to this object" (`&resObj`) it's the same value. So every item being put into `filteredByNameMap` is using the same key/index. As such the length of this is only ever 1 (or 0).

Additionally, each time we try this it has the opportunity to use a new address for the `resObj` used within that loops scope. (I.e. may change the ptr address from `range` to `range`, but not for each object as desired)  So that means some potential solutions begin being ruled out given that the address (used as an ID) needs to be uniform across all scopes within the current execution.

Note: The same type of behaviour would be observed with the `fitlerByNamespace` method too.

Found in my effort to refactor things and add unit tests here: https://github.com/rancher/backup-restore-operator/pull/406 (Added new failing tests)

**Comment by mallardduck** [comment]
This bug - in context of name filtering - would be fixed with my PR to add tests now. Since I added failing tests for it I wanted to fix those as well to make the PR easier to merge without a follow up fix only PR. https://github.com/rancher/backup-restore-operator/pull/406

So that could be merged as a way to further fixing bugs in the existing implementation that fall outside of (loosely) documented spec for the filters. Then with these new limited tests in place to confirm filter behavior larger reafactors could take place with more ease of mind.

**Comment by ericpromislow** [comment]
Fixed by PR #406
