### ISSUE TITLE
[RFE] Azure Storage Account Native Support

### ISSUE THREAD

**Issue by Woovie** [rancher/backup-restore-operator#410]
Presently the backup restore operator supports S3 and existing StorageClasses. These are both great options, especially given the versatility of StorageClass along side CSI drivers.

When backing up to a solution such as Azure's storage accounts or disk, you are required to use some third party solution to interface. These options include:

- [a blob-compatible CSI driver](https://github.com/kubernetes-sigs/blob-csi-driver/) that is not officially supported by Microsoft, made to be used on non-Azure Kubernetes Service (AKS) clusters.
- [an Azure Disk CSI driver](https://github.com/kubernetes-sigs/azuredisk-csi-driver) which is again not officially supported.
- [The official AKS solution](https://learn.microsoft.com/en-us/azure/aks/azure-blob-csi) as a CSI driver.
- Something like MinIO which supports [sending to Azure](https://min.io/docs/minio/linux/administration/object-management/transition-objects-to-azure.html) via [site replication](https://min.io/docs/minio/kubernetes/aks/operations/install-deploy-manage/multi-site-replication.html), adding significant complexity.

While these solutions do work, they are added effort, maintenance, and security. Directly supporting Azure would be a great benefit to Azure customers who lack an S3-compatible solution, as Azure does not have any native S3 support. With Azure storage support, the user experience would be massively improved and effort reduced for those in Azure environments.

**Comment by jbiers** [comment]
Currently BRO handles interactions with S3 via the objectStore package. This package exposes the ObjectStore object and the following functions. They are all tightly coupled to the S3 API.

```
func SetS3Service(bc *v1.S3ObjectStore, accessKey, secretKey string, useSSL bool) (*minio.Client, error)
func GetS3Client(ctx context.Context, objectStore *v1.S3ObjectStore, dynamicClient dynamic.Interface) (*minio.Client, error)
func UploadBackupFile(svc *minio.Client, bucketName, fileName, filePath string) error 
func DownloadFromS3WithPrefix(client *minio.Client, prefix, bucket string) (string, error)
```

The approach here would be to decouple the BRO-specific logic from the S3 interactions (ListObject, GetObject, etc). New private functions can be created in the objectStore package to be used instead of direct calls to S3 API inside of the public functions. This is likely best done creating a Bucket interface.

**Comment by mallardduck** [comment]
Unfortunately this idea would take a very large effort to rebuild some of the core elements of BRO before we could begin cleanly supporting it. As such for now we will have to mark this as `Won't Do`.
