### ISSUE TITLE
Restoring Docker Installs

### ISSUE THREAD

**Issue by SanekP** [rancher/backup-restore-operator#414]
**Rancher Server Setup**
- Rancher version:
Rancher	v2.8.2
Dashboard	v2.8.0
Helm	v2.16.8-rancher2
Machine	v0.15.0-rancher106
- Installation option (Docker install/Helm Chart):
from Marketplace
- Kubernetes Version and Engine:
kubectl version 
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.9", GitCommit:"d1483fdf7a0578c83523bc1e2212a606a44fd71d", GitTreeState:"clean", BuildDate:"2023-09-13T11:32:41Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.6+k3s1", GitCommit:"bd04941a294793ec92e8703d5e5da14107902e88", GitTreeState:"clean", BuildDate:"2023-09-20T23:05:58Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"linux/amd64"}

**Describe the bug**
When trying to restore getting next errors in operator:
INFO[2024/02/12 17:52:16] Marking resource projects.management.cattle.io#v3/local/p-sjvvt for deletion
ERRO[2024/02/12 17:52:16] Error pruning resources: [admission webhook "rancher.cattle.io.projects.management.cattle.io" denied the request: System Project cannot be deleted]
2024-02-12T17:52:16.891561589Z INFO[2024/02/12 17:52:16] Will retry pruning resources by removing finalizers in 10s
INFO[2024/02/12 17:52:26] Retrying pruning resources by removing finalizers
INFO[2024/02/12 17:52:26] Processing controllerRef apps/v1/deployments/rancher
INFO[2024/02/12 17:52:26] Error getting object for controllerRef apps/v1/deployments/rancher: deployments.apps "rancher" not found
ERRO[2024/02/12 17:52:26] error syncing 'restore-blt2f': handler restore: error pruning during restore: [admission webhook "rancher.cattle.io.projects.management.cattle.io" denied the request: System Project cannot be deleted], requeuing

**To Reproduce**
1. Spin-up new cluster: docker run --privileged -d --name rancher -p 443:443 rancher/rancher
2. Install Rancher Backups v103.0.0+up4.0.0
3. Do the backup
4. Stop and remove rancher container
5. Spin-up new cluster: docker run --privileged -d --name rancher -p 443:443 rancher/rancher
6. Install Rancher Backups v103.0.0+up4.0.0
7. Create restore configuration

**Expected behavior**
Cluster is restored. No errors.

**Screenshots**

**Additional context**
I know that there is separate instruction for the Docker installation https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/backup-restore-and-disaster-recovery/restore-docker-installed-rancher. I'm not sure if this is by design that backup-operator doesn't support Docker installation. I thought that "docker" instruction made for the sake of simplicity when you don't need backup-operator and can just save all files. But the result archive have size of 2.8GB compare to 1.5MB file from backup-operator.

**Comment by ericpromislow** [comment]
FWICT, the docker backup just backs up the file tree that rancher uses, while the backup-restore operator grabs a subset of the current k8s objects, and serializes them to YAML, so it's no surprise that the docker backup is twice the size.

What commands did you run to install the backup-restore operator, run a backup, and then run the restore?

**Comment by ericpromislow** [comment]
I see a different problem, that has nothing to do with pruning, but is probably related due to the appearance of the webhook:

```

Error restoring resource restricted-admin of type management.cattle.io/v3,
Resource=globalroles: restoreResource: err updating resource admission webhook
"rancher.cattle.io.globalroles.management.cattle.io" denied the request:
globalrole: Forbidden: updates to builtIn GlobalRoles for
fields other than 'newUserDefault' are forbidden

Error restoring cluster-scoped resources [error restoring
restricted-admin of type management.cattle.io/v3,
Resource=globalroles: restoreResource: err updating resource admission webhook
"rancher.cattle.io.globalroles.management.cattle.io" denied the request:
globalrole: Forbidden: updates to builtIn GlobalRoles for
fields other than 'newUserDefault' are forbidden]
```

**Comment by SanekP** [comment]
> What commands did you run to install the backup-restore operator, run a backup, and then run the restore?

I did everything from rancher.

Created hostPath volume:
![image](https://github.com/rancher/backup-restore-operator/assets/5805351/aa716bbe-85e4-4b17-9b76-d5d991994bd5)

Installed Rancher Backups from Cluster Tools:
![image](https://github.com/rancher/backup-restore-operator/assets/5805351/ae78535f-ae45-48e5-913c-2e2ad9e98904)
![image](https://github.com/rancher/backup-restore-operator/assets/5805351/4f72b20e-4531-47db-b0fe-a8fb2f9091a7)

For the backup only provided its name:
![image](https://github.com/rancher/backup-restore-operator/assets/5805351/669a97e5-c2a6-4f20-8b18-979399ed5e55)
![image](https://github.com/rancher/backup-restore-operator/assets/5805351/b170fe4a-b3ee-4a6e-b289-7b3f174168e7)

Killed this docker container and ran new one. Then again did steps above to install Rancher Backups.

For the restore provided file name:
![image](https://github.com/rancher/backup-restore-operator/assets/5805351/8ddf546e-7662-4afb-bad5-a6d9d89810b5)
![image](https://github.com/rancher/backup-restore-operator/assets/5805351/09220af3-8385-48d0-8a6d-215837a504d0)

Logs 
[rancher-backup.log](https://github.com/rancher/backup-restore-operator/files/14322525/rancher-backup.log)

**Comment by ericpromislow** [comment]
Thank you. I managed to reproduce the error with a docker-based install of rancher on Ubuntu. Here's what's in the logs, formatted for better readability:

```
Error restoring namespaced resources
[ error restoring u-b4qkhsnliz-admin of type management.cattle.io/v3, 
  Resource=clusterroletemplatebindings: 
  restoreResource: err updating resource 
  Internal error occurred: 
     failed calling webhook "rancher.cattle.io.clusterroletemplatebindings.management.cattle.io": 
     failed to call webhook: 
       Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation/clusterroletemplatebindings.management.cattle.io?timeout=10s": 
           tls: failed to verify certificate: 
           x509: certificate signed by unknown authority error restoring local-fleet-local-owner of type management.cattle.io/v3,
           Resource=clusterroletemplatebindings: 
                restoreResource: err updating resource 
                Internal error occurred: 
                 failed calling webhook
     "rancher.cattle.io.clusterroletemplatebindings.management.cattle.io":
     failed to call webhook: 
     Post
      "https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation/clusterroletemplatebindings.management.cattle.io?timeout=10s":
      tls: failed to verify certificate: 
      x509: certificate signed by unknown authority] 
```
I need to investigate further to determine if this is in fact a breaking restore. The restore did continue, and the logs end with the usual messages I see on a successful restore ("Waiting for CRD ... to become available").

**Comment by ericpromislow** [comment]
Need to know more about what happens on Restore, but I noticed in this configuration that after finishing a restore the admin password was reset to the one set when the backup was made. This isn't surprising, but it doesn't sound 100% desirable to me.

Also, when I selected `Apps > Charts` I got these error messages after doing a restore:

```
configmaps "rancher-charts-0-<GUID>" not found

configmaps "rancher-partner-charts-0-<GUID>" not found

configmaps "rancher-rke2-charts-0-<GUID>" not found
```

**Comment by MKlimuszka** [comment]
We tested a restore on a self-signed HA RKE1 cluster and there are no mentions of "authority" in the logs, nor any error logs. So this appears to be specific to docker installs.

**Comment by mallardduck** [comment]
@SanekP - Hey, I think it would be really beneficial for your use-case to actually use a proper k8s based setup. The crux of the issue is running Rancher directly on Docker requires us to run a k8s instance for the node.

So when you get rid of your rancher container, it deletes the "local" k8s cluster too. Meaning when you attempt to restore Rancher Backup, then you end up on a new cluster - meaning this action is a "migration" not a "restore". And as such you should actually be following the migration docs which specify to use `prune: false` in your Restore job.

HOWEVER, because you directly launching the rancher container (which spins up the k8s) you cannot simply "install Rancher backup first, then restore before starting rancher". Since the `rancher-backup` chart will be expecting/needing k8s not Docker alone.

---

ultimately, as @MKlimuszka said this isn't a supported method for running Rancher. Running it like this is really just intended for short term Demos, not for production use. you would be much better off running RKE1 if you like to use Docker, or even opting to setup a single node k3s to run Rancher on.
