### ISSUE TITLE
Add icon for rancher-backup chart

### ISSUE THREAD

**Issue by mrajashree** [rancher/backup-restore-operator#42]
Add icon/logo for rancher-backup chart (Will be visible while launching the chart from dashboard)

**Comment by sowmyav27** [comment]
**On master-head - commit id: `2ae933e`**

Icon for rancher-backups is available
<img width="1616" alt="Screen Shot 2020-09-29 at 8 37 33 PM" src="https://user-images.githubusercontent.com/26032343/94719021-6f2ff380-0307-11eb-9ac0-905178362613.png">
