### ISSUE TITLE
No Status on the backup and restore CR when a backup is in progress

### ISSUE THREAD

**Issue by sowmyav27** [rancher/backup-restore-operator#43]
**On master-head - commit id: `ec04f7878`**

- Create a backup CR
- The CR's State will be `Active` but no entry in `Status` field while the backup is in progress.
<img width="1650" alt="Screen Shot 2020-09-29 at 9 17 57 AM" src="https://user-images.githubusercontent.com/26032343/94585709-3cb5c600-0235-11eb-9188-29a71fbd34f1.png">

Can we have a state like `In Progress` when the backup is happening? 
Same issue is seen when creating/deploying a Restore CR.

**Comment by maggieliu** [comment]
There is a request to remove the status column and add a "State" column.

**Comment by maggieliu** [comment]
Duplicated of this: https://github.com/rancher/dashboard/issues/1693
@sowmyav27 can you confirm is the above dashboard issue can satisfy this request?

**Comment by sowmyav27** [comment]
This is not seen fixed on latest 2.5-head commit id: `36bb757e5`. Reopening it.
When the backup is in progress, there is no status of the backup
<img width="1018" alt="Screen Shot 2020-11-05 at 2 03 07 PM" src="https://user-images.githubusercontent.com/26032343/98301494-b5641c80-1f6f-11eb-8d46-2622c11112e3.png">
