### ISSUE TITLE
Restoring in a new rancher setup fails

### ISSUE THREAD

**Issue by sowmyav27** [rancher/backup-restore-operator#44]
**On master-head - commit id: `ec04f78`**

- On a rancher HA setup - 1 downstream cluster - 5 nodes
- about 200 downstream empty custom clusters.
- About 1000 roles.
- Take a backup
- Bring down the rancher server. (deleted the nodes)
- Bring up a cluster using rke.
- Install the backup-restore-operator chart on the new cluster using Helm CLI
- Restore from backup using a restore CR and prune must be set to false.
- Restore is stuck in retrying
- Error seen in rancher-backup operator logs:

```
WARN[2020/09/29 16:52:29] Error getting object for controllerRef rancher, skipping it 
ERRO[2020/09/29 16:52:29] Error restoring cluster-scoped resources [error restoring grb-q8tz4 of type management.cattle.io/v3, Resource=globalrolebindings: Internal error occurred: failed calling webhook "rancherauth.cattle.io": Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation?timeout=10s": service "rancher-webhook" not found error restoring grb-9f2b6 of type management.cattle.io/v3, Resource=globalrolebindings: Internal error occurred: failed calling webhook "rancherauth.cattle.io": Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation?timeout=10s": service "rancher-webhook" not found error restoring globalrolebinding-tv42r of type management.cattle.io/v3, Resource=globalrolebindings: Internal error occurred: failed calling webhook "rancherauth.cattle.io": Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation?timeout=10s": service "rancher-webhook" not found error restoring grb-qp9zx of type management.cattle.io/v3, Resource=globalrolebindings: Internal error occurred: failed calling webhook "rancherauth.cattle.io": Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation?timeout=10s": service "rancher-webhook" not found error restoring grb-fxkgj of type management.cattle.io/v3, Resource=globalrolebindings: restoreResource: err updating resource Internal error occurred: failed calling webhook "rancherauth.cattle.io": Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation?timeout=10s": service "rancher-webhook" not found error restoring grb-7hrjw of type management.cattle.io/v3, Resource=globalrolebindings: restoreResource: err updating resource Internal error occurred: failed calling webhook "rancherauth.cattle.io": Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation?timeout=10s": service "rancher-webhook" not found error restoring grb-4jfwv of type management.cattle.io/v3, Resource=globalrolebindings: restoreResource: err updating resource Internal error occurred: failed calling webhook "rancherauth.cattle.io": Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation?timeout=10s": service "rancher-webhook" not found error restoring grb-nkw6c of type management.cattle.io/v3, Resource=globalrolebindings: Internal error occurred: failed calling webhook "rancherauth.cattle.io": Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation?timeout=10s": service "rancher-webhook" not found error restoring grb-qlcsx of type management.cattle.io/v3, Resource=globalrolebindings: Internal error occurred: failed calling webhook "rancherauth.cattle.io": Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation?timeout=10s": service "rancher-webhook" not found error restoring grb-gm4nm of type management.cattle.io/v3, Resource=globalrolebindings: Internal error occurred: failed calling webhook "rancherauth.cattle.io": Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation?timeout=10s": service "rancher-webhook" not found error restoring grb-4fprt of type management.cattle.io/v3, Resource=globalrolebindings: Internal error occurred: failed calling webhook "rancherauth.cattle.io": Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation?timeout=10s": service "rancher-webhook" not found] 
ERRO[2020/09/29 16:52:29] error syncing 'restore-migration-1': handler restore: error restoring cluster-scoped resources, check logs for exact error, requeuing 
INFO[2020/09/29 16:52:29] Restoring from backup new-a9cf8718-53fe-45a9-893e-8754ba49acb6-2020-09-29T16-16-59Z.tar.gz 
INFO[2020/09/29 16:52:29] invoking set s3 service client                

```

**Comment by mrajashree** [comment]
This was failing because of the rancher-webhook. The rancher-webhook chart's validating webhook got restored before its service got created. But now that rancher-webhook is no longer part of rancher's default resource-set for 2.5 we don't have to worry about this. Once we migrate to a new cluster and install rancher, rancher will install the webhook chart. This can be checked by the presence of a secret `sh.helm.release.v1.rancher-webhook.v1` in `cattle-system` ns, and  if you do `kubectl get validatingwebhookconfiguration` it should list `rancher.cattle.io`

**Comment by sowmyav27** [comment]
On a restore to a new rancher setup, it fails in the rancher install step

- Error seen:
```
Error: rendered manifests contain a resource that already exists. Unable to continue with install: ServiceAccount "rancher" in namespace "cattle-system" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "rancher"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "cattle-system"
```

Reopening the issue

**Comment by mrajashree** [comment]
The errors seem related to helm version as per [this](https://github.com/rancher/rancher/issues/29213#issuecomment-700912569). I tried with helm version 3.3.0 and it works.  The version used for installing rancher was 3.0.x as per offline discussion. I think using the same 3.2.x+ version to install rancher on both clusters will resolve this. Moving it over to test to see if that's the case

**Comment by sowmyav27** [comment]
**On master-head - commit id: `2ae933e08`**

- Used helm 3.2.4 version to install Rancher HA setup.
- Take backup b1
- Restore to a new Rancher setup where helm version is 3.2.4
- Install worked using `rancher install` instead. 
- Able to restore successfully and install rancher.
- Take another backup b2 in the new rancher setup. Cluster and users from previous rancher are available. User is able to access/edit the cluster that the user is owner of.

**Comment by Slutzky** [comment]
is there way to restore rancher on the same cluster without downgrading helm version ? 

At poresent, following version is installed. 
`helm version --short
v3.3+unreleased+g9109418`

**Comment by mrajashree** [comment]
@Slutzky A restore on the same cluster can be done by creating the Restore object, follow this guide for that https://rancher.com/docs/rancher/v2.x/en/backups/v2.5/configuration/restore-config/

**Comment by Slutzky** [comment]
hi @mrajashree , I followed this guide to create restore resources : 

`
apiVersion: resources.cattle.io/v1
kind: Restore
metadata:
  creationTimestamp: "2020-11-19T08:04:07Z"
  generateName: restore-
  generation: 1
  name: restore-sql4q
  resourceVersion: "10765788"
  selfLink: /apis/resources.cattle.io/v1/restores/restore-sql4q
  uid: 3444a72c-bfe0-472f-95a8-7432bdffc5fc
spec:
  backupFilename: backup-to-minio-662fcefd-5e96-498b-8dda-ce12df84c943-2020-11-19T00-00-00Z.tar.gz
  deleteTimeoutSeconds: 10
  prune: true
  storageLocation:
    s3:
      bucketName: rancher-backup
      credentialSecretName: rancher-backup-secret-minio
      credentialSecretNamespace: cattle-resources-system
      endpoint: minio.domain.com`

All rancher pods got deleted and cannot be recreated by rancher-backup pod. I see the following error in rancher-backup pod: 




`ERRO[2020/11/19 08:05:07] Error restoring resource cluster-member of type management.cattle.io/v3, Resource=roletemplates: restoreResource: err updating resource Internal error occurred: failed calling webhook "rancherauth.cattle.io": Post https://rancher-webhook.cattle-system.svc:443/v1/webhook/validation?timeout=10s: context deadline exceeded
INFO[2020/11/19 08:05:07] restoreResource: Restoring jailer-timeout of type management.cattle.io/v3, Resource=settings
INFO[2020/11/19 08:05:07] Successfully restored jailer-timeout
INFO[2020/11/19 08:05:07] restoreResource: Restoring no-default-admin of type management.cattle.io/v3, Resource=settings
INFO[2020/11/19 08:05:07] Successfully restored no-default-admin
INFO[2020/11/19 08:05:07] restoreResource: Restoring ui-k8s-default-version-range of type management.cattle.io/v3, Resource=settings
INFO[2020/11/19 08:05:07] Successfully restored ui-k8s-default-version-range
INFO[2020/11/19 08:05:07] restoreResource: Restoring keycloak of type management.cattle.io/v3, Resource=authconfigs
INFO[2020/11/19 08:05:07] Successfully restored keycloak
INFO[2020/11/19 08:05:07] restoreResource: Restoring project-monitoring-readonly of type management.cattle.io/v3, Resource=roletemplates`
