### ISSUE TITLE
Mutliple scheduled backups created for hourly recurring backup using backup-restore-operator

### ISSUE THREAD

**Issue by dnoland1** [rancher/backup-restore-operator#49]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Add the rancher-backups app in the Cluster Explorer - Apps. Configure it to use an S3 endpoint.
2. Add a new scheduled backup with cron `45 * * * *`, retention count set to 100
3. Wait until 45 minutes after the hour.

**Result:**
Saw 13 backups. Only should see one:
![image](https://user-images.githubusercontent.com/468462/94892197-e913ca00-0438-11eb-8b51-4eeca4a7a9c8.png)
rancher-backup log:
[rancher-backup-5c5bcd7f44-5vg9c.log](https://github.com/rancher/rancher/files/5319137/rancher-backup-5c5bcd7f44-5vg9c.log)

**Other details that may be helpful:**
Checked back next day and backups were created every hour at 45 minutes passed the hour.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.5.0-rc4

- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by mrajashree** [comment]
This is an edge case, can be reproduced by:
1. Create a recurring backup CR, to be taken at every "Nth" minute, where N is current time+1, meaning if right now it's 12:01 PM, creating recurring backup with schedule `2 * * * *`
2. At times can be reproduced with `@every 1m`

**Comment by sowmyav27** [comment]
**Reproduced this issue on 2.5-head - commit id: `ce572b5f15`**

- Create a recurring backup CR - to be taken at every "Nth" minute, where N is current time+1
- Current time then - 12:40
<img width="976" alt="Screen Shot 2020-10-02 at 12 43 50 PM" src="https://user-images.githubusercontent.com/26032343/94963397-f4a0d880-04ac-11eb-98f7-8b2977ef6ff9.png">

- Saw multiple recurring backups
<img width="1566" alt="Screen Shot 2020-10-02 at 12 42 28 PM" src="https://user-images.githubusercontent.com/26032343/94963426-fb2f5000-04ac-11eb-8908-05d26e9c5010.png">

**Comment by mrajashree** [comment]
Can be tested with chart version 1.0.200 (operator tag v1.0.2) -> should be the only ones available in dropdown while launching chart

**Comment by sowmyav27** [comment]
**On v2.5-head commit id: `ce572b5f1`**

- Create a recurring backup CR - to be taken at every "Nth" minute, where N is current time+1
- Current time then - 3:53

<img width="1505" alt="Screen Shot 2020-10-02 at 3 55 06 PM" src="https://user-images.githubusercontent.com/26032343/94975804-a9e08a00-04c7-11eb-8857-fe4efd251efc.png">

- Additional backups are not seen
- Only one taken at the time of backup creating and one at 3.54 when schedule was given as:

<img width="965" alt="Screen Shot 2020-10-02 at 3 56 18 PM" src="https://user-images.githubusercontent.com/26032343/94975852-d3011a80-04c7-11eb-9011-dbb6e51d44c4.png">
