### ISSUE TITLE
Update wrangler version when updating k8s 1.20

### ISSUE THREAD

**Issue by mrajashree** [rancher/backup-restore-operator#52]

**Comment by cbron** [comment]
See: https://github.com/rancher/rancher/pull/29344

**Comment by mrajashree** [comment]
Moving out to 2.5.3 as discussed with @deniseschannon

**Comment by maggieliu** [comment]
@mrajashree Is this update needed for backup/restore feature?

**Comment by mrajashree** [comment]
@maggieliu the bug fix from wrangler isn't needed in backup-restore-operator because the operator doesn't use that function from wrangler. But we can still update wrangler version to the latest one in 2.5.4

**Comment by deniseschannon** [comment]
Since backup-restore doesn't use this, this can be closed.
