### ISSUE TITLE
[UI] Rancher Backups UI should default Encryption option to Encrypted

### ISSUE THREAD

**Issue by mallardduck** [rancher/backup-restore-operator#554]
Users can still quite easily opt out to use unencrypted backups.
However lets make the form match the suggested option of using encryption.

PR here: https://github.com/rancher/dashboard/pull/11609

This idea came as a result of a conversation between O&B squad and some of our QA+PIT friends.

**Comment by izaac** [comment]
Validated on Rancher version: `v2.10-695357ad2fdb58bfce027ecf6ce96e8a4e3ddbab-head`
UI: `master d5024a1`

I used an S3 storage for the backups configuration but this also works with the default storage.
The option for Encrypted is selected by Default. The user can opt-out easily selecting unencrypted if they prefer.

![Image](https://github.com/user-attachments/assets/273b7e80-e79c-4d87-b03e-4470e5a1b3a3)
