### ISSUE TITLE
rancher v2.5.2 did not restore namespace cattle-logging-system from backup

### ISSUE THREAD

**Issue by stoneshi-yunify** [rancher/backup-restore-operator#58]
env: rancher v2.5.2, single node k8s cluster

To recreate:
- install rancher-backup in app&marketplace, config local store (local pv)
- install rancher-logging in app&marketplace (namespace `cattle-logging-system`)
- take a backup
- delete namespace `cattle-logging-system`
- restore from backup, but found nothing was restored in namespace `cattle-logging-system`

No error found in rancher-backup operator logs.

question:
- Rancher doc says: `The backup-restore operator needs to be installed in the local cluster, and only backs up the Rancher app. `, so what exactly apps/namespaces does rancher-backup support? Is there a plan to support non-rancher apps/namespaces?

Thanks very much.

**Comment by mrajashree** [comment]
Hi @stoneshi-yunify 
Can you check the backup tar file which you are using for restore, to see if it contains the namespace?
You can untar that file and find the folder for namespaces, it should contain a json file named cattle-logging-system.json
That will tell us if it was backed up properly
