### ISSUE TITLE
Cluster migration: Issues when restored to a new cluster with Rancher installed

### ISSUE THREAD

**Issue by sowmyav27** [rancher/backup-restore-operator#6]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Steps to reproduce (least amount of steps as possible):**

- Create a HA on rke. Create a custom cluster, node templates, users, roles, template revisions
- Take a backup
- Delete this HA, bring up a new HA on EKS cluster with rancher installed
- Restore from backup to this cluster

**Issues:**
- cluster (present earlier) is stuck in Unavailable state. Some error in rancher logs
```
2020/08/28 22:19:17 [ERROR] failed to start cluster controllers c-pjhjc: context canceled
2020/08/28 22:19:51 [ERROR] error syncing 'c-pjhjc': handler cluster-deploy: Get "https://3.129.25.80:6443/apis/apps/v1/namespaces/cattle-system/daemonsets/cattle-node-agent": waiting for cluster [c-pjhjc] agent to connect, requeuing
2020/08/28 22:20:26 [INFO] Active TLS secret serving-cert (ver=10665) (count 9): map[field.cattle.io/projectId:local:p-fh7md listener.cattle.io/cn-10.42.0.3:10.42.0.3 listener.cattle.io/cn-10.42.1.5:10.42.1.5 listener.cattle.io/cn-10.42.2.6:10.42.2.6 listener.cattle.io/cn-127.0.0.1:127.0.0.1 listener.cattle.io/cn-172.31.23.22:172.31.23.22 listener.cattle.io/cn-172.31.31.67:172.31.31.67 listener.cattle.io/cn-172.31.45.28:172.31.45.28 listener.cattle.io/cn-localhost:localhost listener.cattle.io/hash:<>]
2020/08/28 22:21:30 [INFO] Stopping cluster agent for c-pjhjc
2020/08/28 22:21:30 [ERROR] failed to start cluster controllers c-pjhjc: context canceled
2020/08/28 22:23:30 [INFO] Stopping cluster agent for c-pjhjc
2020/08/28 22:23:30 [ERROR] failed to start cluster controllers c-pjhjc: context canceled
```
- namespaces/projects - messed up. (snapshot)
<img width="1453" alt="Screen Shot 2020-08-28 at 3 22 48 PM" src="https://user-images.githubusercontent.com/26032343/91624892-e9133c80-e957-11ea-971b-14696a9b65b9.png">

- some error in the backup-restore container
```
INFO[2020/08/28 21:42:05] Will retry pruning resources by removing finalizers in 0s
INFO[2020/08/28 21:42:05] Retrying pruning resources by removing finalizers
INFO[2020/08/28 21:42:06] Processing controllerRef apps/v1/deployments/rancher
INFO[2020/08/28 21:42:06] Scaling up controllerRef apps/v1/deployments/rancher to 3
INFO[2020/08/28 21:42:06] Done restoring
E0828 21:47:57.305691       1 reflector.go:380] pkg/mod/k8s.io/client-go@v0.18.0/tools/cache/reflector.go:125: Failed to watch *v1.Backup: the server has asked for the client to provide credentials (get backups.meta.k8s.io)
E0828 21:47:57.310833       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.0/tools/cache/reflector.go:125: Failed to list *v1.Backup: Unauthorized
E0828 21:47:59.021907       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.0/tools/cache/reflector.go:125: Failed to list *v1.Backup: Unauthorized
E0828 21:48:02.728944       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.0/tools/cache/reflector.go:125: Failed to list *v1.Backup: Unauthorized
E0828 21:48:09.755693       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.0/tools/cache/reflector.go:125: Failed to list *v1.Backup: Unauthorized
E0828 21:48:26.413138       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.0/tools/cache/reflector.go:125: Failed to list *v1.Backup: Unauthorized
E0828 21:49:05.208455       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.0/tools/cache/reflector.go:125: Failed to list *v1.Backup: Unauthorized
E0828 21:49:38.306123       1 reflector.go:380] pkg/mod/k8s.io/client-go@v0.18.0/tools/cache/reflector.go:125: Failed to watch *v1.Restore: the server has asked for the client to provide credentials (get restores.meta.k8s.io)
E0828 21:49:38.311219       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.0/tools/cache/reflector.go:125: Failed to list *v1.Restore: Unauthorized
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.0-alpha1
- Installation option (single install/HA): HA

**Comment by sowmyav27** [comment]
Verified another backup restore use case

Steps taken on the initial Rancher server
- Deployed one hosted EKS cluster
- Deployed GKE cluster
- Created Cluster template - with 2 revisions - created a cluster from this template
- Deployed 1 Custom cluster  3 nodes all roles Istio enabled in this setup
- Deployed node driver cluster - DO
- Deployed a windows cluster 
- Deployed Few Secrets in each downstream cluster level
- Catalogs/ repos added in each downstream cluster level. Deployed apps
- Take a backup b1
- Restore from this in a new setup (all the above deployed clusters' nodes are available.
- Bring up a new Rancher setup with the same DNS
- Restore from the backup b1
- Noticed the following

- - Isito and minitoring are not enabled in the cluster.
- - apps/catalogs deployed are fine.
- - EKS cluster is stuck in waiting state as the eks-controller-operator did not deploy.
- - Other clusters have come up Active.
- - namespaces/projects - messed up in the local cluster. namespaces available previously in a project is now part of `Namespace: All`

**Comment by mrajashree** [comment]
@sowmyav27 was this restore done with prune set to false? like I said for namespaces/projects, we should try either prune set to false or restore first and then bring up rancher, otherwise restore will end up deleting the default and system projects

**Comment by sowmyav27** [comment]
@mrajashree  
- The default for "prune" was set so it must have been set to true. Will check what happens when you set prune to false.
- Isito was enabled on the cluster - Tools --> istio --> Enable which in turn deploys the app.
- A hosted EKS cluster was created.

**Comment by sowmyav27** [comment]
When prune is set to `false`:
- The old setup's local nodes are seen imported in the new cluster. A total of 6 nodes - 3 from old setup, 3 from the new setup are seen
- The projects "Default" and "System" are seen 2 times in the local cluster.

**Comment by sowmyav27** [comment]
@mrajashree As per offline discussion to confirm if these are all the dashboard CRDS which have to be added in the rancher-resource-set
```
kubectl get crds | grep catalog.cattle.io
clusterrepos.catalog.cattle.io                                  2020-09-08T17:38:19Z
operations.catalog.cattle.io                                    2020-09-08T17:38:19Z
releases.catalog.cattle.io                                      2020-09-08T17:38:19Z
```
Other CRDs missing from rancher-resource-set include v2 apps, v1 apps (monitoring, istio), eks controller

**Comment by mrajashree** [comment]
The only way to not mess up namespaces in projects, is to launch the operator and create restore from backup and then start rancher. Tested that this works
Otherwise if you launch rancher first and then restore, I'll check what can be done about the two "default" & "system" projects and double "local" cluster nodes. Might have to remove them manually

**Comment by mrajashree** [comment]
The steps to install described [here](https://github.com/rancher/backup-restore-operator/issues/24#issuecomment-692339527) will resolve the projects+namespaces issue.
I also see monitoring and istio working on the downstream clusters after migration, so maybe these steps take care of that too. I have a charts PR open to include the changes required for CRDs from catalog.cattle.io and EKS-operator resources

**Comment by mrajashree** [comment]
@sowmyav27 The charts PR is merged, it contains the correct resourceSet for eks-operator and catalog.cattle.io CRs. I tested that monitoring and istio stays enabled on downstream clusters after resource. And with the steps for migrating cluster that were shared yesterday, the projects and namespaces are restored correctly

**Comment by sowmyav27** [comment]
**Scenario to test:**

- Enable Istio on a downstream cluster - can use jenkins job
- Enable Monitoring on a downstream cluster
- Deploy a hosted EKS cluster
- Verify `catalog.cattle.io CRs` are available in the resource set and when a backup is created these are backed up.

**After restore verify:**

- projects and namespaces are restored correctly
- Hosted EKS cluster comes up and Edit on the EKS cluster, add node group. Edit should work
- Add a new hosted EKS cluster. Cluster should come up fine
- Monitoring and Istio should be enabled and working on the downstream clusters

Logging a separate issue for resource set for v2 charts

**Comment by sowmyav27** [comment]
@mrajashree will confirm if the resource set will need to include `catalog.cattle.io` or just `clusterrepos.catalog.cattle.io`

**Comment by soumyalj** [comment]
Tested with restoring to new RKE cluster using master-head(33f755f18)

- Enable Istio on a downstream cluster - can use jenkins job
- Enable Monitoring on a downstream cluster
- Deploy a hosted EKS cluster
- Verify catalog.cattle.io should be available as part or the resource set now.
- Add a repo in dashboard and deploy an app from this repo
- Perform a backup bkp1

Restore to bkp1 on a new RKE cluster. After restore verify:
 
- Projects and namespaces are restored correctly - **Done**
- Hosted EKS cluster comes up and Edit on the EKS cluster. Cluster goes to updating state and edit should succeed - **Done**
- Add a new hosted EKS cluster. Cluster should come up fine - **Done**
- Monitoring and Istio should be enabled and working on the downstream clusters . Monitoring and Istio pods are running - **Done**
- Verify the custom repo and app deployed are available after restore. - **Done**

**Comment by sowmyav27** [comment]
Fix for [this](https://github.com/rancher/backup-restore-operator/issues/6#issuecomment-693726348) is tracked [here](https://github.com/rancher/backup-restore-operator/issues/32)

**Comment by sowmyav27** [comment]
Verified on master-head - commit id: `f8bad` (restored setup)

On the initial setup:
- Enable Istio on a downstream cluster 
- Enable Monitoring on a downstream cluster
- Deploy a hosted EKS cluster
- Verify catalog.cattle.io should be available as part or the resource set now.
- Add a repo in dashboard and deploy an app from this repo
- Perform a backup bkp1

Restore to bkp1 on a new RKE cluster. After restore verified:
 
- Projects and namespaces are restored correctly 
- Hosted EKS cluster comes up and Edit on the EKS cluster. Cluster goes to updating state and edit succeeded
- Add a new hosted EKS cluster. Cluster comes up fine
- Monitoring and Istio should be enabled and working on the downstream clusters . Monitoring and Istio pods are running 
- Verified the custom repo is available. (app--)

**Comment by sowmyav27** [comment]
As per offline discussion - Only components core to Rancher control plane will be backed up. v2 apps in the local cluster will not be backed up. They can be redeployed after a restore.
