### ISSUE TITLE
rancher-backup fails to install from UI - error in s3-secret.yaml template

### ISSUE THREAD

**Issue by oskapt** [rancher/backup-restore-operator#67]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

- install rancher-backup-operator from Apps in 2.5
- choose S3 as the default storage provider

**Result:**

`Error: YAML parse error on rancher-backup/templates/s3-secret.yaml: error converting YAML to JSON: yaml: line 23: could not find expected ':' `

**Other details that may be helpful:**

- using minio as endpoint
- secret configured and selected
- this seems to have something to do with `folder` in the template - tried both with and without a folder. same error.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.3
- Installation option (single install/HA): k3s

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): k3s
- Machine type (cloud/VM/metal) and specifications (CPU/memory): KVM
- Kubernetes version (use `kubectl version`): 1.19.4+k3s1

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by ansilh** [comment]
The certificate string passed should be base64 encrypted in the first place (k8s will encrypt it again as bas64 as its part of Secret) else the CA value will be considered as a file path instead of a string.
https://github.com/rancher/backup-restore-operator/blob/master/pkg/objectstore/s3minio.go#L245

**Comment by mrajashree** [comment]
What @ansilh says is right, the cert should be base64 encoded. Was it encoded while configuring this operator?
Can we try installing this chart with the exact values and do a `helm template` instead to see which value is the error for at line 23?

**Comment by ddsmith2-eprod** [comment]
This issue is still relevant in Rancher 2.7.1.  If you create an s3 secret with Rancher to configure etcd backups, then try and install Rancher backups using the same secret you get this error on a new default cluster setup.

**Comment by oskapt** [comment]
@ddsmith2-eprod since this was auto-closed in 2022, you're better off opening a new issue and referencing this one. no one is assigned to this issue anymore, so it's unlikely that your report will be seen.
