### ISSUE TITLE
multinode docker based backup

### ISSUE THREAD

**Issue by myhellone** [rancher/backup-restore-operator#68]
Hi!
How to make Rancher (docker based installation) multi node cluster backup 
I have rancher 2.5,  master and 3 worker node. 

I see rancher backup operator in localc cluster but this is not working for my cluster setup.

**Comment by mrajashree** [comment]
Hi @myhellone just to confirm, you want to move your rancher running in a docker container to an HA setup (running in a cluster) right? 
You can install the operator on your local cluster in the docker setup and follow the [migration docs](https://rancher.com/docs/rancher/v2.x/en/backups/v2.5/migrating-rancher/) to restore it onto a new cluster. Are you any errors?

**Comment by myhellone** [comment]
Hi, I don't have HA. I have one master node and 3 worker nodes, this is for lab but i don't want to loose my data, I see rancher backup in local cluster, but cant install rancher backup in my second cluster "production"
