### ISSUE TITLE
Add Rancher Operator to the ResourceSet

### ISSUE THREAD

**Issue by nickgerace** [rancher/backup-restore-operator#72]
Parent issue: https://github.com/rancher/backup-restore-operator/issues/69

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `2f2cfe6`**

- Install a HA setup on 2.5-head
- deploy two downstream clusters
- Add a git repo in continuous Delivery Tab in Cluster explorer
- Verify the apps are deployed And on continuous Delivery Tab in Cluster explorer, Clusters are seen Active
- Deploy rancher-backup `rancher-backup:1.0.400-rc02` and take a backup b1
- Followed these steps to migrate to a new Rancher setup- https://rancher.com/docs/rancher/v2.x/en/backups/v2.5/migrating-rancher/ (`rancher-backup:1.0.400-rc02` is installed)
- On the new Rancher setup, added new cluster.
- git repo in continuous Delivery Tab in Cluster explorer is deployed on the new cluster successfully.
