### ISSUE TITLE
Can't restore from Google Storage 

### ISSUE THREAD

**Issue by fewkso** [rancher/backup-restore-operator#76]
The code uses ListObjectsV2 which isn't supported by the google storage api. 

https://github.com/rancher/backup-restore-operator/blob/master/pkg/objectstore/s3minio.go#L170

Errror on restore: 
```
ERRO[2021/02/24 01:54:11] failed to list objects in backup buckets [bucketname]: 
A header or query you provided requested a function that is not implemented.
```

minio fixed it in mc: https://github.com/minio/mc/pull/3101/files#diff-be74cc7510906e23a9983b3164a5dc6e383e0bb2cde5adf62d54ae89e844c3c6

isGoogle(c.targetURL.Host) basically compares the Host value with "storage.googleapis.com"

in minio-go, they offer a ListObjects func that accepts a useV1 option: https://github.com/minio/minio-go/blob/7f05f7e9774ec1860922ce5bf2f6717faf8677aa/api-list.go#L641

I tested just by removing the "V2" from ListObjectsV2 and ran my custom image and the restore worked.

thx,
Eric

gz#15493

**Comment by bluemalkin** [comment]
@fewkso how were you able to use Google storage from the chart ?

**Comment by fewkso** [comment]
> @fewkso how were you able to use Google storage from the chart ?

In GCS settings I created an access key, created a secret and then I configured the chart like this:

secret file:
```apiVersion: v1
kind: Secret
metadata:
  name: rancher-backup-creds
  namespace: cattle-resources-system
type: Opaque
data:
  accessKey: $RANCHER_BACKUP_ACCESS_KEY
  secretKey: $RANCHER_BACKUP_SECRET_KEY
```

values file:
```s3:
  enabled: true
  credentialSecretName: rancher-backup-creds
  credentialSecretNamespace: cattle-resources-system
  region: northamerica-northeast1
  bucketName: bucket-backup-data
  folder: rancher-ha
  endpoint: storage.googleapis.com```
  
  This works for backup, but then, the restore fails because GCS api doesn't support v2 calls, thus this issue.

**Comment by fmarceau-imagia** [comment]
+1 for this bug, same issue here as well !

**Comment by superseb** [comment]
### Root cause

Unable to use Google Cloud Storage as backend
 
### What was fixed, or what changes have occurred
Added support to use a different function to use Google Cloud Storage 

### Areas or cases that should be tested
Regular S3 usage (and/or Minio) and using Google Cloud Storage as backend

### What areas could experience regressions?
Regular S3 usage (and/or Minio) 

### Are the repro steps accurate/minimal?
- Use Google Cloud Storage as S3 backend for backup-restore-operator

**Comment by MSpencer87** [comment]
_Verified on 2.6.5-rc8_

**Steps to Reproduce:**
1. Create Google Storage Bucket
2. Create an Access Key (Settings->Interoperability->Access keys for your user account)
3. Bring up Rancher 2.6.5-rc8
4. Install Rancher Backups
5. Create Resources(i.e. users, cluster templates etc)
6. Create s3 Backup to Google Store using the credentials created in Step 2.
7. Create more Resources(i.e. users, cluster templates etc)
8. Restore from s3 Backup on Google Storage (No Errors)
