### ISSUE TITLE
Create an operator to backup and restore rancher

### ISSUE THREAD

**Issue by mrajashree** [rancher/backup-restore-operator#8]
For the backup/restore controllers
- [x] Get CRD fields, api version finalized in design meeting
- [x] Backup controller should gather resources specified in resourceSet
- [x] Restore controller should create/update any resources present in backup
- [x] Restore controller should by default prune resources present on the cluster that match the resourceSet but were not a part of the backup
- [x] Restore controller should preserve ownerReferences that are allowed by k8s design. Although [as per k8s docs](https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/), cross-namespaced ownerRefs and clusterscoped objects having namespaced owners is disallowed, [kubernetes has a bug](https://github.com/kubernetes/kubernetes/issues/65200) where it allows creation of such objects and enforces the ownerRefs. Such objects will get restore without ownerRefs. Controller will log these resources.
- [x] Accept controllerRefs to scale down before restore and scale back up after restore
- [x] Support recurring backups, delete them as per the retention policy
- [x] Support local and s3/minio as storage locations
- [x] Encrypt resources such as secrets before storing at the backup location. Decrypt during restore

**Comment by sowmyav27** [comment]
This is being validated on master-head.
separate tickets have been logged any related issues. Closing this issue
