### ISSUE TITLE
Add AKS Operator to the ResourceSet

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/backup-restore-operator#81]
Rancher issue: https://github.com/rancher/rancher/issues/31282

**Comment by jiaqiluo** [comment]
available in rancher-backup chart version 1.1.100+up1.1.1

**Comment by sowmyav27** [comment]
**Using rancher-backup chart version `1.1.100+up1.1.1` on master-head commit id: `b2f88241`**

Followed [this docs](https://rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-k8s/) to restore to a new cluster

**Steps:**

- Deploy a HA rancher setup on master-head
- Deploy rancher backups chart
- Deploy an AKS cluster - cluster1
- Take a backup b1
- Bring up another RKE k8s cluster and install rancher-backups on it. 
- Restore from backup b1
- Install cert manager and rancher master-head on this cluster
- `cluster1` is seen active state. Edit and add a nodepool to this cluster, and cluster provisions and comes up Active
- Add a new AKS and DO node driver clusters. Both the clusters come up Active.
