### ISSUE TITLE
Restore Rancher from K3s to GKE leaves the local cluster stuck in Upgrading

### ISSUE THREAD

**Issue by philipsparrow** [rancher/backup-restore-operator#83]
Steps to reproduce:
Rancher cluster running on K3s
Backup to S3
Create (new) GKE cluster
Restore k3s backup to GKE cluster (prune: false)

`local` cluster is still configured as `K3s` and is stuck in `Cluster is being upgraded`

I had this happen on 2 different attempts so I suspect this is a problem with restoring the local cluster configuration when there is no local cluster yet.

**Comment by kuldazbraslav** [comment]
I'm running into similar issue with migrating from single node Docker version (which is k3s internally) to kops-built kubernetes cluster on AWS.

`local` cluster is still configured as `k3s`, marked as `Active` and doesn't load any nodes.

**Comment by kuldazbraslav** [comment]
It would actually be great to ignore the local cluster at all.
