### ISSUE TITLE
s3-endpoint-ca is not a valid x509 certificate

### ISSUE THREAD

**Issue by rpelissi** [rancher/backup-restore-operator#88]
Hi,
I am running rancher 2.5.7 on k3s cluster v1.20.4+k3s1.
In order to do the rancher backup, I have setup and s3 minio storage on my Truenas server. I even created a CA and certificate so I can use hostname to connect to it. s3 service is started and I have created the bucket.
Now, when I setup the backup on rancher and provide the infos it fails.
If I upload (read from file) my CA certificate the the endpoint CA field, when I save the job I got an error message:
`open -----BEGIN CERTIFICATE----- MIIEYTCCA0mgAwIBAgIDRhF+MA0GCSqGSIb3DQEBCwUAMIGtMRswGQYDVQQDDBJu YXMuZGlnaXRhbHJhdC5sYW4xCzAJBgNVBAYTAkNBMQ8wDQYDVQQIDAZRdWViZWMx FzAVBgNVBAcMDkRldXgtTW9udGFnbmVzMRMwEQYDVQQKDApEaWdpdGFscmF0MRcw FQYDVQQLDA5kaWdpdGFscmF0LmxhbjEpMCcGCSqGSIb3DQEJARYacm9tYWluLnBl bGlzc2llckBnbWFpbC5jb20wHhcNMjEwNDA4MTgxNjIwWhcNMjMwNzEyMTgxNjIw WjCBrTEbMBkGA1UEAwwSbmFzLmRpZ2l0YWxyYXQubGFuMQswCQYDVQQGEwJDQTEP MA0GA1UECAwGUXVlYmVjMRcwFQYDVQQHDA5EZXV4LU1vbnRhZ25lczETMBEGA1UE CgwKRGlnaXRhbHJhdDEXMBUGA1UECwwOZGlnaXRhbHJhdC5sYW4xKTAnBgkqhkiG 9w0BCQEWGnJvbWFpbi5wZWxpc3NpZXJAZ21haWwuY29tMIIBIjANBgkqhkiG9w0B AQEFAAOCAQ8AMIIBCgKCAQEA2bSa+l/grvtzxEmkxj19AwG9KP77SaoT5nuDLF7L 3yJCnpj++bkp7JHWMJaoH2/8cUEzSezF+8//UJhabvwCQrwnf0zMsUlWw2TKeCTU fzHcFOeDcp7pZbJSpFLpoairmdbsGIgzL/LmkFPwbueJTJjf6T2/9iCd/T2jtbqn 8+cU26UshzM32W5gI0X1A9zxcxRx1KCES3WTo0PXUUUMu3sFZOvwaT2/zJxDECly D3lr2iz3i/jrnmHpMaTSSCOf9zaLw4EyhHZIJMT45+qeSDT9+LuOCXUAgJRbuSNT vxcZBrkjFIPLiXZGDL0Dk4pxwrBfbsnlG/ES1G9xC90v+wIDAQABo4GHMIGEMC0G A1UdEQQmMCSCEm5hcy5kaWdpdGFscmF0LmxhboIOZGlnaXRhbHJhdC5sYW4wHQYD VR0OBBYEFN5tVjPSKojgpnwkBlxvumWDvtAwMA8GA1UdEwEB/wQFMAMBAf8wEwYD VR0lBAwwCgYIKwYBBQUHAwEwDgYDVR0PAQH/BAQDAgEGMA0GCSqGSIb3DQEBCwUA A4IBAQB+NiC0FqPBYTJzgPeOl5Qe7oOtYPokumQa2Fk2q74pSXhWyctihn5etWFM xlO3vMeWk6Zn0GuoKXxR1dSytJbkNadLT4fxW2RFm9O5iEM02Fkrq7NMOuslZcfY RDE4Vba0NIjLZaxnPEX7IRTlho6IV2r829q2FMKJBA0c0Ihw/0fWrJkypz84FXaP lQS4xA263cj0nglAUCa5UgNWXDHDWUNri5cEBfyKWi1R+R5HylkEX1DibqVeKyVN FDbFg0AGau9wljx0h14NuFdco7oq4D8+WX8NiXL8/UnXV93l5grdOhiGbgbm9tJ6 53R+8XgiPaSnOiVmgPAmeOkSljpC -----END CERTIFICATE----- : file name too long `

If I go using only the data and copy/paste it like:
`MIIETjCCAzagAwIBAgIEAJT14zANBgkqhkiG9w0BAQsFADCBrjEbMBkGA1UEAwwSbmFzLmRpZ2l0YWxyYXQubGFuMQswCQYDVQQGEwJDQTEQMA4GA1UECAwHUXXDqWJlYzEXMBUGA1UEBwwORGV1eC1Nb250YWduZXMxEzARBgNVBAoMCkRpZ2l0YWxSYXQxFzAVBgNVBAsMDmRpZ2l0YWxyYXQubGFuMSkwJwYJKoZIhvcNAQkBFhpyb21haW4ucGVsaXNpc2VyQGdtYWlsLmNvbTAeFw0yMTA0MDgxNTM4NDlaFw0yMzA3MTIxNTM4NDlaMIGuMRswGQYDVQQDDBJuYXMuZGlnaXRhbHJhdC5sYW4xCzAJBgNVBAYTAkNBMRAwDgYDVQQIDAdRdcOpYmVjMRcwFQYDVQQHDA5EZXV4LU1vbnRhZ25lczETMBEGA1UECgwKRGlnaXRhbFJhdDEXMBUGA1UECwwOZGlnaXRhbHJhdC5sYW4xKTAnBgkqhkiG9w0BCQEWGnJvbWFpbi5wZWxpc2lzZXJAZ21haWwuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp8OvbL3mPZi1enNhTBDMcIKQ+VjL83+YtmTfzBY5fdkrneSwUCDcsC6myxPFW3Gapyxjkfw7ceIp6UdF+EfdtaaGFVste4ege66Qflukdt0t4rV0TdeLmYiXA2npdHfiUSmFW8N8TGR7G2UmkVjburjU5h5p95J4zWg7rgqQ0mrakpqH0Mfek7ccin1EVxGmY0V0nY57zaXw8MBJfJVSh3D15DNBiZGDrkwsz4X9tbqxav3Ip2XoeKm3A/tqIKxnOdpbl1rxGqZgl5sAINTkcWdUa6hAmTLDO5+srIed1yu7QuhU7ML7FhMQA6IHGq80a651S/nYfwX/x3DdvashwwIDAQABo3IwcDAZBgNVHREEEjAQgg5kaWdpdGFscmF0LmxhbjAdBgNVHQ4EFgQU8BuKMT7jFNutLhysK/SerVf4MP0wDwYDVR0TAQH/BAUwAwEB/zATBgNVHSUEDDAKBggrBgEFBQcDATAOBgNVHQ8BAf8EBAMCAQYwDQYJKoZIhvcNAQELBQADggEBAGesctN9yeKglyz9nblcIEMW5XhejN7fP4dAM2FW8qhJnSUtj1g+qRfec/j096EBZv+9yGIsDwMTHqh3BMoqHyF1Dltd7PGnzkuFTJ1CULxPpmIqcUlYBzHoig4ODzEL0Qo9+JVkYLcau2alO4O6nZDSRf74GIYEC53yCYPbiG3XTbGrNytoV3H2jn7QVcyKb9dKyCrsg4ZzJ6ElZPNNfakUxXlJF6v+RsrdueUxp+9hi2jk2kJFlDpoNIsX8d7ApG+gw86zXEgdQXymRcrQc6oClF7+MF833vaW+hCFE42MC5O5L0k0fRQvs64ohQF5vYaGit3wTHAH0OTCL9zf`

I got:`
s3-endpoint-ca is not a valid x509 certificate `

I have check this home made certificate and it seems to be valid so I don't know what is wrong there...

Any advices will be more than welcome.
Thanks!

**Comment by mrajashree** [comment]
@rpelissi the operator expects base64 encoded cert, can you encode the cert and then provide it as input to try?

**Comment by rpelissi** [comment]
Hi,
Thanks for the answer. I have tested the string below on this online decoder tools : https://www.google.com/search?client=firefox-b-d&q=x509+certificate+base64+decode so I know the certificate is base64 encoded and valid, at least for what I know.

MIIETjCCAzagAwIBAgIEAJT14zANBgkqhkiG9w0BAQsFADCBrjEbMBkGA1UEAwwSbmFzLmRpZ2l0YWxyYXQubGFuMQswCQYDVQQGEwJDQTEQMA4GA1UECAwHUXXDqWJlYzEXMBUGA1UEBwwORGV1eC1Nb250YWduZXMxEzARBgNVBAoMCkRpZ2l0YWxSYXQxFzAVBgNVBAsMDmRpZ2l0YWxyYXQubGFuMSkwJwYJKoZIhvcNAQkBFhpyb21haW4ucGVsaXNpc2VyQGdtYWlsLmNvbTAeFw0yMTA0MDgxNTM4NDlaFw0yMzA3MTIxNTM4NDlaMIGuMRswGQYDVQQDDBJuYXMuZGlnaXRhbHJhdC5sYW4xCzAJBgNVBAYTAkNBMRAwDgYDVQQIDAdRdcOpYmVjMRcwFQYDVQQHDA5EZXV4LU1vbnRhZ25lczETMBEGA1UECgwKRGlnaXRhbFJhdDEXMBUGA1UECwwOZGlnaXRhbHJhdC5sYW4xKTAnBgkqhkiG9w0BCQEWGnJvbWFpbi5wZWxpc2lzZXJAZ21haWwuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp8OvbL3mPZi1enNhTBDMcIKQ+VjL83+YtmTfzBY5fdkrneSwUCDcsC6myxPFW3Gapyxjkfw7ceIp6UdF+EfdtaaGFVste4ege66Qflukdt0t4rV0TdeLmYiXA2npdHfiUSmFW8N8TGR7G2UmkVjburjU5h5p95J4zWg7rgqQ0mrakpqH0Mfek7ccin1EVxGmY0V0nY57zaXw8MBJfJVSh3D15DNBiZGDrkwsz4X9tbqxav3Ip2XoeKm3A/tqIKxnOdpbl1rxGqZgl5sAINTkcWdUa6hAmTLDO5+srIed1yu7QuhU7ML7FhMQA6IHGq80a651S/nYfwX/x3DdvashwwIDAQABo3IwcDAZBgNVHREEEjAQgg5kaWdpdGFscmF0LmxhbjAdBgNVHQ4EFgQU8BuKMT7jFNutLhysK/SerVf4MP0wDwYDVR0TAQH/BAUwAwEB/zATBgNVHSUEDDAKBggrBgEFBQcDATAOBgNVHQ8BAf8EBAMCAQYwDQYJKoZIhvcNAQELBQADggEBAGesctN9yeKglyz9nblcIEMW5XhejN7fP4dAM2FW8qhJnSUtj1g+qRfec/j096EBZv+9yGIsDwMTHqh3BMoqHyF1Dltd7PGnzkuFTJ1CULxPpmIqcUlYBzHoig4ODzEL0Qo9+JVkYLcau2alO4O6nZDSRf74GIYEC53yCYPbiG3XTbGrNytoV3H2jn7QVcyKb9dKyCrsg4ZzJ6ElZPNNfakUxXlJF6v+RsrdueUxp+9hi2jk2kJFlDpoNIsX8d7ApG+gw86zXEgdQXymRcrQc6oClF7+MF833vaW+hCFE42MC5O5L0k0fRQvs64ohQF5vYaGit3wTHAH0OTCL9zf

I do not know go and I am not sure how I can check what's going on with the decode..
Thanks!

**Comment by rpelissi** [comment]
If I undertand the PEM cetificate format, is is already base64 encoded. All online tools that I have tested can decode my certificate so I really don't know what is the issue..

**Comment by mikekuzak** [comment]
same issue here with Rancher 2.5.5 and rancher-backup v1.0.300. Whatever I try just can't get this damn thing to work.

**Comment by mikekuzak** [comment]
@mrajashree @rpelissi 

The only workaround that worked for me is this:
![image](https://user-images.githubusercontent.com/18675587/128909341-5d7cb932-96bb-4545-a87b-17097fdb64a3.png)

Go into container, create the file with the cert. 

![image](https://user-images.githubusercontent.com/18675587/128909671-49b57268-6ee7-4539-9baf-34f829c06aa2.png)

and now it's working.

**Comment by rrossouw01** [comment]
@ mikekuzak thanks I am also able to add the file inside the container and that worked.  This is a bug correct?  Iit should not be necessary to add the file inside the container every restart.  Apart form why can't it be pasted directly or works with Read from file button could it not be an option to pick it from secrets as TLS secret?

**Comment by dcottone** [comment]
@rpelissi you need to encode base 64 the full CA file content:

-----BEGIN CERTIFICATE-----
MIIE...........................
.........0Q0myktVwhRzOyom
-----END CERTIFICATE-----

because the function that read the endpointCA

```
func readS3EndpointCA(endpointCA string) ([]byte, error) {
        // I expect the CA to be passed as base64 string OR a file system path.
        // I do this to be able to pass it through rke/rancher api without writing it
        // to the backup container filesystem.
        ca, err := base64.StdEncoding.DecodeString(endpointCA)
        if err == nil {
                log.Info("reading s3-endpoint-ca as a base64 string")
        } else {
                ca, err = ioutil.ReadFile(endpointCA)
                log.Infof("reading s3-endpoint-ca from [%v]", endpointCA)
        }
        return ca, err
}

```

try to decode it or read from a file.
So the full certificate need to be encoded again.

Regards
