### ISSUE TITLE
Make PVC name customisable in backup-restore-operator

### ISSUE THREAD

**Issue by ibrokethecloud** [rancher/backup-restore-operator#94]
Using backup-restore operator with a storage class for persistence of snapshots results in a pvc claim being suffixed with the Helm ReleaseRevision.

This means each time an update to the backup-restore-operator is rolled out it results in a new pvc claim being created.

```
{{/*
Create PVC name using release and revision number.
*/}}
{{- define "backupRestore.pvcName" -}}
{{- printf "%s-%d" .Release.Name .Release.Revision }}
{{- end }} 
```

We should either re-use pvc name or allow the users to customize the PVC name so they can reuse existing PV's.

**Comment by sowmyav27** [comment]
Hi @MKlimuszka Can you confirm if this has to go in `2.7.0` or `2023-Q1-v2.7x` ? cc: @bmdepesa

**Comment by nickwsuse** [comment]
`Verified on v2.7-head ID: 9278cf1`

Persistent Volume Claim (PVC) names are staying the same after the version of Rancher Backups changes, and no new PVCs are being made on upgrade.
