### ISSUE TITLE
Add podSecurityPolicy as an optional resource

### ISSUE THREAD

**Issue by jessievar** [rancher/backup-restore-operator#98]
The `rancher-backup` chart doesn't have a podSecurityPolicy created for the `backup-restore-operator` deployment. It won't work on any cluster that has PodSecurityPolicy admission controller enabled. Before PodSecurityPolicy is officially deprecated and removed from k8s we still need the policy available in the chart for the application to work with the admission controller.

Note that the serivice account is bound to the `cluster-admin` role, so maybe a new role with psp permission?

**Comment by yucongvar** [comment]
Jessie Lin

**Comment by jiaqiluo** [comment]
This is tracked on this issue https://github.com/rancher/backup-restore-operator/issues/29
